PROGRAM MAIN_CUCALLN_MF 

USE MODEL_PHYSICS_ECMWF_MOD      , ONLY : MODEL_PHYSICS_ECMWF_TYPE
USE MODEL_PHYSICS_SIMPLINEAR_MOD , ONLY : MODEL_PHYSICS_SIMPLINEAR_TYPE
USE YOERAD                       , ONLY : TERAD
USE YOM_YGFL                     , ONLY : TYPE_GFLD
USE YOMCHEM                      , ONLY : TCHEM
USE SPP_MOD                      , ONLY : TSPP_CONFIG
USE PARKIND1                     , ONLY : JPIM     ,JPRB
USE YOMHOOK                      , ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMCST                       , ONLY : TCST  
USE YOETHF                       , ONLY : TTHF 
USE YOMPERTPAR                   , ONLY : TPERTPAR

USE UTIL_MODEL_PHYSICS_ECMWF_TYPE_MOD
USE UTIL_MODEL_PHYSICS_SIMPLINEAR_TYPE_MOD
USE UTIL_TERAD_MOD
USE UTIL_TYPE_GFLD_MOD
USE UTIL_TCHEM_MOD
USE UTIL_TSPP_CONFIG_MOD
USE UTIL_TCST_MOD
USE UTIL_TTHF_MOD
USE UTIL_TPERTPAR_MOD

USE YOMDATA
USE YOMRMSE

USE YOMALLOC
USE XRD_GETOPTIONS
USE XRD_UNIX_ENV

USE YOMHOOK

#include "stack.h"

USE STACK_MOD

USE CUCALLN_MF_LOKI_MOD

USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : STDOUT => OUTPUT_UNIT

IMPLICIT NONE


REAL(KIND=JPRB)                      :: PPLDARE
REAL(KIND=JPRB)                      :: PPLRG
INTEGER(KIND=JPIM)                   :: KSTEP
TYPE(TTHF)                           :: YDTHF
TYPE(TCST)                           :: YDCST
TYPE(TERAD)                          :: YDERAD
TYPE(MODEL_PHYSICS_SIMPLINEAR_TYPE)  :: YDML_PHY_SLIN
TYPE(MODEL_PHYSICS_ECMWF_TYPE)       :: YDML_PHY_EC
TYPE(TYPE_GFLD)                      :: YGFL
TYPE(TCHEM)                          :: YDCHEM
TYPE(TSPP_CONFIG)                    :: YDSPP_CONFIG
TYPE(TPERTPAR)                       :: YDPERTPAR
INTEGER(KIND=JPIM)                   :: KLON,KGPBLKS
INTEGER(KIND=JPIM)                   :: KSMAX 
INTEGER(KIND=JPIM)                   :: KLEV 
INTEGER(KIND=JPIM)                   :: KSPPN2D
INTEGER(KIND=JPIM)                   :: KTRAC 
LOGICAL                              :: LDMCAPEA
LOGICAL                              :: LDSLPHY 
REAL(KIND=JPRB)                      :: PTSPHY 
REAL(KIND=JPRB)                      :: PVDIFTS
LOGICAL                           , POINTER  :: LDLAND(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLCRIT_AER(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTM1(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PQM1(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PUM1(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PVM1(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PCM1(:,:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLITOT(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PVERVEL(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PQHFL(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PAHFS(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PAPHM1(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PAP(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PAPH(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PGEO(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PGEOH(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENT(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENQ(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENU(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENV(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENTA(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENQA(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PGAW(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PCUCONVCA(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PGP2DSPP(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PSCAV(:) 
REAL(KIND=JPRB)                   , POINTER  :: PSCAV0(:) 
REAL(KIND=JPRB)                   , POINTER  :: PDX(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENC(:,:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PARPRC(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KTOPC(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KBASEC(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KTYPE(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KCBOT(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KCTOP(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KCBOT_LIG(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KCTOP_LIG(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KBOTSC(:,:)
LOGICAL                           , POINTER  :: LDCUM(:,:)
LOGICAL                           , POINTER  :: LDCUM_LIG(:,:)
LOGICAL                           , POINTER  :: LDSC(:,:)
LOGICAL                           , POINTER  :: LDSHCV(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLU(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLUDE(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLUDELI(:,:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PSNDE(:,:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PMFU(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PMFD(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLGLAC(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PDIFCQ(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PDIFCS(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFHPCL(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFHPCN(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFPLCL(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFPLCN(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLRAIN(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PRSUD(:,:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PSTRCU(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PSTRCV(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFCQLF(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFCQIF(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PMFUDE_RATE(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PMFDDE_RATE(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PCAPE(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PWMEAN(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PVDISCU(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PWU(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PDISS(:,:,:)

LOGICAL                           , POINTER  :: LDLAND_INI(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLCRIT_AER_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTM1_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PQM1_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PUM1_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PVM1_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PCM1_INI(:,:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLITOT_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PVERVEL_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PQHFL_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PAHFS_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PAPHM1_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PAP_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PAPH_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PGEO_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PGEOH_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENT_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENQ_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENU_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENV_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENTA_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENQA_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PGAW_INI(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PCUCONVCA_INI(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PGP2DSPP_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PSCAV_INI(:) 
REAL(KIND=JPRB)                   , POINTER  :: PSCAV0_INI(:) 
REAL(KIND=JPRB)                   , POINTER  :: PDX_INI(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PTENC_INI(:,:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PARPRC_INI(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KTOPC_INI(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KBASEC_INI(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KTYPE_INI(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KCBOT_INI(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KCTOP_INI(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KCBOT_LIG_INI(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KCTOP_LIG_INI(:,:)
INTEGER(KIND=JPIM)                , POINTER  :: KBOTSC_INI(:,:)
LOGICAL                           , POINTER  :: LDCUM_INI(:,:)
LOGICAL                           , POINTER  :: LDCUM_LIG_INI(:,:)
LOGICAL                           , POINTER  :: LDSC_INI(:,:)
LOGICAL                           , POINTER  :: LDSHCV_INI(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLU_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLUDE_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLUDELI_INI(:,:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PSNDE_INI(:,:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PMFU_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PMFD_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLGLAC_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PDIFCQ_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PDIFCS_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFHPCL_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFHPCN_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFPLCL_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFPLCN_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PLRAIN_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PRSUD_INI(:,:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PSTRCU_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PSTRCV_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFCQLF_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PFCQIF_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PMFUDE_RATE_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PMFDDE_RATE_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PCAPE_INI(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PWMEAN_INI(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PVDISCU_INI(:,:)
REAL(KIND=JPRB)                   , POINTER  :: PWU_INI(:,:,:)
REAL(KIND=JPRB)                   , POINTER  :: PDISS_INI(:,:,:)
#include "cucalln_mf.intfb.h"

INTEGER :: JLON, JBLK
INTEGER :: ILUNCI, ILUNFI, ILUNFO, IOUT
INTEGER :: NPROMA, NGPBLKS
CHARACTER (LEN=128) :: CLOUT
CHARACTER (LEN=128) :: CLCASE_IN
CHARACTER (LEN=128) :: CLCASE_OUT
TYPE (DD12), POINTER :: YLD
LOGICAL :: LLVERBOSE, LLDIFF, LLRMSE
INTEGER, POINTER :: IBLOCKLIST (:)
TYPE(STACK) :: YLSTACK
INTEGER :: ISIZE4, ISIZE8
CHARACTER*64 :: CLMETHOD
INTEGER :: ITIME, NTIME
LOGICAL :: LLSAVE, LLEXIST
REAL(KIND=8) :: TSC, TEC, TSD, TED, ZTC, ZTD, TSCOPY, TECOPY, TCOPY

#ifdef ARCH
CHARACTER (LEN=*), PARAMETER :: CLARCH = ARCH
#else
CHARACTER (LEN=*), PARAMETER :: CLARCH = 'unkwown'
#endif

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

INTEGER(KIND=JPIM) :: NGPTOT 
INTEGER(KIND=JPIM) :: JKGLO
INTEGER(KIND=JPIM) :: KIDIA 
INTEGER(KIND=JPIM) :: KFDIA 
INTEGER(KIND=JPIM) :: IBL
INTEGER(KIND=JPIM) :: IOFF 


IF (LHOOK) CALL DR_HOOK ('MAIN_CUCALLN_MF', 0, ZHOOK_HANDLE)

YLD => NULL ()

CALL INITOPTIONS

NPROMA  = 0; CALL GETOPTION ("--nproma",  NPROMA)
NGPBLKS = 0; CALL GETOPTION ("--ngpblks", NGPBLKS)

CALL GETOPTION ("--case-in", CLCASE_IN, MND=.TRUE.)
CLCASE_OUT = ''; CALL GETOPTION ("--case-out", CLCASE_OUT)

CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--rmse", LLRMSE)

#ifdef PARKIND1_SINGLE
ISIZE4 = 80; 
ISIZE8 = 10; 
#else
ISIZE4 = 10; 
ISIZE8 = 80; 
#endif
CALL GETOPTION ("--stack-size-4", ISIZE4)
CALL GETOPTION ("--stack-size-8", ISIZE8)
NTIME = 1; CALL GETOPTION ("--times", NTIME)

CLMETHOD = 'openmp'; CALL GETOPTION ("--method", CLMETHOD)

IBLOCKLIST => NULL ()
CALL GETOPTION ("--block-list", IBLOCKLIST)

LLSAVE = CLCASE_OUT /= ''

IF (LLSAVE) THEN
  CALL XRD_MKDIR (TRIM (CLCASE_OUT))
ENDIF

CLOUT = '-'; CALL GETOPTION ("--out", CLOUT)

CALL CHECKOPTIONS

CALL LOADALL

IF (LLVERBOSE) THEN
WRITE (0, *) " NPROMA = ", NPROMA, " NGPBLKS = ", NGPBLKS, " KLEV = ", KLEV
WRITE (0, *) " ISIZE4 = ", ISIZE4, " ISIZE8 = ", ISIZE8, " NTIME = ", NTIME
ENDIF

IF (LLSAVE) THEN
  CALL SAVEIALL
ENDIF

CALL COPY_INI 
CALL GET_TIME (TSD)

!$ACC DATA COPY (PDX, LDLAND, PTM1, PQM1, PUM1, PVM1, PLITOT, PVERVEL, PQHFL, PAHFS, PAPHM1, PAP, PAPH, PGEO, PGEOH, &
!$ACC&           PGAW, PCUCONVCA, PGP2DSPP, PTENT, PTENQ, PTENU, PTENV, PTENTA, PTENQA, PARPRC, KTOPC, KBASEC, KTYPE, &
!$ACC&           KCBOT, KCTOP, KBOTSC, LDCUM, LDSC, KCBOT_LIG, KCTOP_LIG, LDCUM_LIG, LDSHCV, PLCRIT_AER, PLU, PLUDE, &
!$ACC&           PLUDELI, PSNDE, PMFU, PMFD, PLGLAC, PDIFCQ, PDIFCS, PFHPCL, PFHPCN, PFPLCL, PFPLCN, PLRAIN, PRSUD, &
!$ACC&           PSTRCU, PSTRCV, PFCQLF, PFCQIF, PMFUDE_RATE, PMFDDE_RATE, PCAPE, PWU, PWMEAN, PVDISCU, PDISS, PCM1, &
!$ACC&           PTENC, PSCAV, PSCAV0) IF (TRIM (CLMETHOD) == 'openaccsinglecolumn')

IF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN
  CALL COPY (YDTHF)
  CALL COPY (YDCST)
  CALL COPY (YDERAD)
  CALL COPY (YDML_PHY_SLIN)
  CALL COPY (YDML_PHY_EC)
  CALL COPY (YGFL)
  CALL COPY (YDCHEM)
  CALL COPY (YDSPP_CONFIG)
  CALL COPY (YDPERTPAR)
ENDIF

CALL GET_TIME (TSC)

DO ITIME = 1, NTIME

  IF (TRIM (CLMETHOD) == 'openmp') THEN
  
!$OMP PARALLEL DO PRIVATE (IBL) 
    DO IBL = 1, NGPBLKS
    
      CALL CUCALLN_MF   (PPLDARE, PPLRG, KSTEP, YDTHF, YDCST, YDERAD, YDML_PHY_SLIN, YDML_PHY_EC, YGFL,               &
      & YDCHEM, YDSPP_CONFIG, YDPERTPAR, 1_JPIM, NPROMA, NPROMA, KSMAX, KLEV, PDX (:, IBL), KSPPN2D,                 &
      & LDMCAPEA, LDLAND (:, IBL), LDSLPHY, PTSPHY, PVDIFTS, PTM1 (:, :, IBL), PQM1 (:, :, IBL), PUM1 (:, :, IBL),&
      & PVM1 (:, :, IBL), PLITOT (:, :, IBL), PVERVEL (:, :, IBL), PQHFL (:, :, IBL), PAHFS (:, :, IBL),         &
      & PAPHM1 (:, :, IBL), PAP (:, :, IBL), PAPH (:, :, IBL), PGEO (:, :, IBL), PGEOH (:, :, IBL),              &
      & PGAW (:, IBL), PCUCONVCA (:, IBL), PGP2DSPP (:, :, IBL), PTENT (:, :, IBL), PTENQ (:, :, IBL),           &
      & PTENU (:, :, IBL), PTENV (:, :, IBL), PTENTA (:, :, IBL), PTENQA (:, :, IBL), PARPRC (:, IBL),           &
      & KTOPC (:, IBL), KBASEC (:, IBL), KTYPE (:, IBL), KCBOT (:, IBL), KCTOP (:, IBL), KBOTSC (:, IBL),       &
      & LDCUM (:, IBL), LDSC (:, IBL), KCBOT_LIG (:, IBL), KCTOP_LIG (:, IBL), LDCUM_LIG (:, IBL),               &
      & LDSHCV (:, IBL), PLCRIT_AER (:, :, IBL), PLU (:, :, IBL), PLUDE (:, :, IBL), PLUDELI (:, :, :, IBL),     &
      & PSNDE (:, :, :, IBL), PMFU (:, :, IBL), PMFD (:, :, IBL), PLGLAC (:, :, IBL), PDIFCQ (:, :, IBL),        &
      & PDIFCS (:, :, IBL), PFHPCL (:, :, IBL), PFHPCN (:, :, IBL), PFPLCL (:, :, IBL), PFPLCN (:, :, IBL),      &
      & PLRAIN (:, :, IBL), PRSUD (:, :, :, IBL), PSTRCU (:, :, IBL), PSTRCV (:, :, IBL), PFCQLF (:, :, IBL),    &
      & PFCQIF (:, :, IBL), PMFUDE_RATE (:, :, IBL), PMFDDE_RATE (:, :, IBL), PCAPE (:, IBL), PWU (:, :, IBL),   &
      & PWMEAN (:, IBL), PVDISCU (:, IBL), PDISS (:, :, IBL), KTRAC, PCM1 (:, :, :, IBL), PTENC (:, :, :, IBL),  &
      & PSCAV, PSCAV0)
    
    ENDDO
  
  ELSEIF (TRIM (CLMETHOD) == 'openmpsinglecolumn') THEN
  
    YSTACK%IALIGN = 8 
    IF (ISIZE4 > 0) ALLOCATE (YSTACK%ZDATA4 (NPROMA, KLEV, ISIZE4, NGPBLKS))
    IF (ISIZE8 > 0) ALLOCATE (YSTACK%ZDATA8 (NPROMA, KLEV, ISIZE8, NGPBLKS))
    
    NGPTOT = NGPBLKS*NPROMA
!$OMP PARALLEL DO PRIVATE (JKGLO, IBL, KIDIA, KFDIA, IOFF, YLSTACK)
    DO JKGLO=1,NGPTOT,NPROMA
      KIDIA = 1
      KFDIA = MIN(NPROMA, NGPTOT - JKGLO + 1)
      IBL = (JKGLO - 1) / NPROMA + 1
      !#YLSTACK_L = LOC(ZSTACK(1, IBL))
      IOFF = JKGLO
    
      YLSTACK%L8 = stack_l8 (YSTACK, IBL, NGPBLKS)
      YLSTACK%U8 = stack_u8 (YSTACK, IBL, NGPBLKS)
      YLSTACK%L4 = stack_l4 (YSTACK, IBL, NGPBLKS)
      YLSTACK%U4 = stack_u4 (YSTACK, IBL, NGPBLKS)

      CALL CUCALLN_MF_LOKI(PPLDARE, PPLRG, KSTEP, YDTHF, YDCST, YDERAD, YDML_PHY_SLIN, YDML_PHY_EC, YGFL,         &
        & YDCHEM, YDSPP_CONFIG, YDPERTPAR, KIDIA, KFDIA, NPROMA, KSMAX, KLEV, PDX (:, IBL), KSPPN2D,                     &
        & LDMCAPEA, LDLAND (:, IBL), LDSLPHY, PTSPHY, PVDIFTS, PTM1 (:, :, IBL), PQM1 (:, :, IBL), PUM1 (:, :, IBL),&
        & PVM1 (:, :, IBL), PLITOT (:, :, IBL), PVERVEL (:, :, IBL), PQHFL (:, :, IBL), PAHFS (:, :, IBL),         &
        & PAPHM1 (:, :, IBL), PAP (:, :, IBL), PAPH (:, :, IBL), PGEO (:, :, IBL), PGEOH (:, :, IBL),              &
        & PGAW (:, IBL), PCUCONVCA (:, IBL), PGP2DSPP (:, :, IBL), PTENT (:, :, IBL), PTENQ (:, :, IBL),           &
        & PTENU (:, :, IBL), PTENV (:, :, IBL), PTENTA (:, :, IBL), PTENQA (:, :, IBL), PARPRC (:, IBL),           &
        & KTOPC (:, IBL), KBASEC (:, IBL), KTYPE (:, IBL), KCBOT (:, IBL), KCTOP (:, IBL), KBOTSC (:, IBL),       &
        & LDCUM (:, IBL), LDSC (:, IBL), KCBOT_LIG (:, IBL), KCTOP_LIG (:, IBL), LDCUM_LIG (:, IBL),               &
        & LDSHCV (:, IBL), PLCRIT_AER (:, :, IBL), PLU (:, :, IBL), PLUDE (:, :, IBL), PLUDELI (:, :, :, IBL),     &
        & PSNDE (:, :, :, IBL), PMFU (:, :, IBL), PMFD (:, :, IBL), PLGLAC (:, :, IBL), PDIFCQ (:, :, IBL),        &
        & PDIFCS (:, :, IBL), PFHPCL (:, :, IBL), PFHPCN (:, :, IBL), PFPLCL (:, :, IBL), PFPLCN (:, :, IBL),      &
        & PLRAIN (:, :, IBL), PRSUD (:, :, :, IBL), PSTRCU (:, :, IBL), PSTRCV (:, :, IBL), PFCQLF (:, :, IBL),    &
        & PFCQIF (:, :, IBL), PMFUDE_RATE (:, :, IBL), PMFDDE_RATE (:, :, IBL), PCAPE (:, IBL), PWU (:, :, IBL),   &
        & PWMEAN (:, IBL), PVDISCU (:, IBL), PDISS (:, :, IBL), KTRAC, PCM1 (:, :, :, IBL), PTENC (:, :, :, IBL),  &
        & PSCAV, PSCAV0, YDSTACK_L=YLSTACK%L8)
    
    ENDDO
  
  ELSEIF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN
  

    YSTACK%IALIGN = 8 
  IF (ITIME == 1) THEN
    ALLOCATE (YSTACK%ZDATA4 (NPROMA, KLEV, ISIZE4, NGPBLKS))
    ALLOCATE (YSTACK%ZDATA8 (NPROMA, KLEV, ISIZE8, NGPBLKS))


!$ACC ENTER DATA CREATE (YSTACK%ZDATA4)
!$ACC ENTER DATA CREATE (YSTACK%ZDATA8)

!$ACC ENTER DATA CREATE (YSTACK)
!$ACC UPDATE DEVICE (YSTACK)
!$ACC ENTER DATA ATTACH (YSTACK%ZDATA4)
!$ACC ENTER DATA ATTACH (YSTACK%ZDATA8)
  ENDIF
    


    
!#    !$acc&present (YDTHF, YDCST, YDERAD, YDML_PHY_SLIN, YDML_PHY_EC, YGFL, YDCHEM, YDSPP_CONFIG, YDPERTPAR, YSTACK, &
!#    !$acc&         PDX, LDLAND, PTM1, PQM1, PUM1, PVM1, PLITOT, PVERVEL, PQHFL, PAHFS, PAPHM1, PAP, PAPH, PGEO, PGEOH, &
!#    !$acc&         PGAW, PCUCONVCA, PGP2DSPP, PTENT, PTENQ, PTENU, PTENV, PTENTA, PTENQA, PARPRC, KTOPC, KBASEC, KTYPE, &
!#    !$acc&         KCBOT, KCTOP, KBOTSC, LDCUM, LDSC, KCBOT_LIG, KCTOP_LIG, LDCUM_LIG, LDSHCV, PLCRIT_AER, PLU, PLUDE, &
!#    !$acc&         PLUDELI, PSNDE, PMFU, PMFD, PLGLAC, PDIFCQ, PDIFCS, PFHPCL, PFHPCN, PFPLCL, PFPLCN, PLRAIN, PRSUD, &
!#    !$acc&         PSTRCU, PSTRCV, PFCQLF, PFCQIF, PMFUDE_RATE, PMFDDE_RATE, PCAPE, PWU, PWMEAN, PVDISCU, PDISS, PCM1, &
!#    !$acc&         PTENC, PSCAV, PSCAV0) &
     NGPTOT = NGPBLKS*NPROMA
    !$acc parallel loop gang vector_length( KLON ) &
    !$acc private( YLSTACK, JKGLO, KIDIA, KFDIA, IBL, IOFF)
     DO JKGLO=1,NGPTOT,NPROMA
       KIDIA = 1
       KFDIA = MIN(NPROMA, NGPTOT - JKGLO + 1)
       IBL = (JKGLO - 1) / NPROMA + 1
       !#YLSTACK_L = LOC(ZSTACK(1, IBL))
       IOFF = JKGLO

       YLSTACK%L8 = stack_l8 (YSTACK, IBL, NGPBLKS)
       YLSTACK%U8 = stack_u8 (YSTACK, IBL, NGPBLKS)
       YLSTACK%L4 = stack_l4 (YSTACK, IBL, NGPBLKS)
       YLSTACK%U4 = stack_u4 (YSTACK, IBL, NGPBLKS)

       CALL CUCALLN_MF_LOKI(PPLDARE, PPLRG, KSTEP, YDTHF, YDCST, YDERAD, YDML_PHY_SLIN, YDML_PHY_EC, YGFL,         &
        & YDCHEM, YDSPP_CONFIG, YDPERTPAR, KIDIA, KFDIA, NPROMA, KSMAX, KLEV, PDX (:, IBL), KSPPN2D,                     &
        & LDMCAPEA, LDLAND (:, IBL), LDSLPHY, PTSPHY, PVDIFTS, PTM1 (:, :, IBL), PQM1 (:, :, IBL), PUM1 (:, :, IBL),&
        & PVM1 (:, :, IBL), PLITOT (:, :, IBL), PVERVEL (:, :, IBL), PQHFL (:, :, IBL), PAHFS (:, :, IBL),         &
        & PAPHM1 (:, :, IBL), PAP (:, :, IBL), PAPH (:, :, IBL), PGEO (:, :, IBL), PGEOH (:, :, IBL),              &
        & PGAW (:, IBL), PCUCONVCA (:, IBL), PGP2DSPP (:, :, IBL), PTENT (:, :, IBL), PTENQ (:, :, IBL),           &
        & PTENU (:, :, IBL), PTENV (:, :, IBL), PTENTA (:, :, IBL), PTENQA (:, :, IBL), PARPRC (:, IBL),           &
        & KTOPC (:, IBL), KBASEC (:, IBL), KTYPE (:, IBL), KCBOT (:, IBL), KCTOP (:, IBL), KBOTSC (:, IBL),       &
        & LDCUM (:, IBL), LDSC (:, IBL), KCBOT_LIG (:, IBL), KCTOP_LIG (:, IBL), LDCUM_LIG (:, IBL),               &
        & LDSHCV (:, IBL), PLCRIT_AER (:, :, IBL), PLU (:, :, IBL), PLUDE (:, :, IBL), PLUDELI (:, :, :, IBL),     &
        & PSNDE (:, :, :, IBL), PMFU (:, :, IBL), PMFD (:, :, IBL), PLGLAC (:, :, IBL), PDIFCQ (:, :, IBL),        &
        & PDIFCS (:, :, IBL), PFHPCL (:, :, IBL), PFHPCN (:, :, IBL), PFPLCL (:, :, IBL), PFPLCN (:, :, IBL),      &
        & PLRAIN (:, :, IBL), PRSUD (:, :, :, IBL), PSTRCU (:, :, IBL), PSTRCV (:, :, IBL), PFCQLF (:, :, IBL),    &
        & PFCQIF (:, :, IBL), PMFUDE_RATE (:, :, IBL), PMFDDE_RATE (:, :, IBL), PCAPE (:, IBL), PWU (:, :, IBL),   &
        & PWMEAN (:, IBL), PVDISCU (:, IBL), PDISS (:, :, IBL), KTRAC, PCM1 (:, :, :, IBL), PTENC (:, :, :, IBL),  &
        & PSCAV, PSCAV0, YDSTACK_L=YLSTACK%L8)
    
    ENDDO


  ENDIF


  IF (ITIME /= NTIME) THEN
    CALL GET_TIME (TSCOPY)
    CALL COPY_RESET
    CALL GET_TIME (TECOPY)
    TCOPY = TCOPY + TECOPY - TSCOPY
  ENDIF

ENDDO

CALL GET_TIME (TEC)

IF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN
  CALL WIPE (YDPERTPAR)
  CALL WIPE (YDSPP_CONFIG)
  CALL WIPE (YDCHEM)
  CALL WIPE (YGFL)
  CALL WIPE (YDML_PHY_EC)
  CALL WIPE (YDML_PHY_SLIN)
  CALL WIPE (YDERAD)
  CALL WIPE (YDCST)
  CALL WIPE (YDTHF)
ENDIF

!$ACC END DATA

CALL GET_TIME (TED)

ZTC = TEC - TSC - TCOPY
ZTD = TED - TSD - TCOPY

LLEXIST = .FALSE.

IF (CLOUT == '-') THEN
  IOUT = STDOUT
ELSE
  IOUT = 77
  INQUIRE (FILE=TRIM (CLOUT), EXIST=LLEXIST)
  IF (LLEXIST) THEN
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='OLD', POSITION='APPEND')
  ELSE
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='NEW')
  ENDIF
ENDIF

IF (.NOT. LLEXIST) &
WRITE (IOUT, '(A16,";",A32,";",A8,";",A8,";",A8,4(";",A20))') &
              & "CLARCH", "CLMETHOD", "NPROMA", "NGPBLKS", "NTIME", &
              & "ZTCTOT", "ZTC", "ZTDTOT", "ZTD"

WRITE (IOUT, '(A16,";",A32,";",I8,";",I8,";",I8,4(";",E20.10))') &
              & CLARCH,  TRIM (CLMETHOD), NPROMA, NGPBLKS, NTIME, &
              & ZTC, ZTC / REAL (NPROMA*NGPBLKS*NTIME, 8), &
              & ZTD, ZTD / REAL (NPROMA*NGPBLKS*NTIME, 8)

IF (IOUT /= STDOUT) THEN
  CLOSE (IOUT)
ENDIF


IF (LLRMSE) THEN
  CALL RMSEALL
ENDIF
IF (LLDIFF) THEN
  CALL DIFFALL
ENDIF

IF (LLSAVE) THEN
  CALL SAVEOALL
ENDIF

IF (LHOOK) CALL DR_HOOK ('MAIN_CUCALLN_MF', 1, ZHOOK_HANDLE)

CONTAINS

SUBROUTINE LOADALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.IN.dat',    FORM='UNFORMATTED')

CALL LOAD (ILUNCI, PPLDARE)
CALL LOAD (ILUNCI, PPLRG)
CALL LOAD (ILUNCI, KSTEP)
CALL LOAD (ILUNCI, YDTHF)
CALL LOAD (ILUNCI, YDCST)
CALL LOAD (ILUNCI, YDERAD)
CALL LOAD (ILUNCI, YDML_PHY_SLIN)
CALL LOAD (ILUNCI, YDML_PHY_EC)
CALL LOAD (ILUNCI, YGFL)
CALL LOAD (ILUNCI, YDCHEM)
CALL LOAD (ILUNCI, YDSPP_CONFIG)
CALL LOAD (ILUNCI, YDPERTPAR)
CALL LOAD (ILUNCI, KLON)
CALL LOAD (ILUNCI, KGPBLKS)


IF (NPROMA == 0) NPROMA = KLON
IF (NGPBLKS == 0) THEN
  IF (ASSOCIATED (IBLOCKLIST)) THEN
    NGPBLKS = SIZE (IBLOCKLIST)
  ELSE
    NGPBLKS = KGPBLKS
  ENDIF
ENDIF

IF ((NPROMA /= KLON) .OR. (NGPBLKS /= KGPBLKS) .OR. ASSOCIATED (IBLOCKLIST)) THEN

  ALLOCATE (YLD)

  IF (ASSOCIATED (IBLOCKLIST)) THEN
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS], IBLOCKLIST)
  ELSE
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS])
  ENDIF
  
  NPROMA = YLD%IPROMA2
  NGPBLKS = YLD%IGPBLKS2

ENDIF

KLON = NPROMA
KGPBLKS = NGPBLKS


CALL LOAD (ILUNCI, KSMAX)
CALL LOAD (ILUNCI, KLEV)
CALL LOAD (ILUNFI, PDX,                  YDD=YLD)
CALL LOAD (ILUNCI, KSPPN2D)
CALL LOAD (ILUNCI, LDMCAPEA)
CALL LOAD (ILUNFI, LDLAND,               YDD=YLD)
CALL LOAD (ILUNCI, LDSLPHY)
CALL LOAD (ILUNCI, PTSPHY)
CALL LOAD (ILUNCI, PVDIFTS)
CALL LOAD (ILUNFI, PTM1,                 YDD=YLD)
CALL LOAD (ILUNFI, PQM1,                 YDD=YLD)
CALL LOAD (ILUNFI, PUM1,                 YDD=YLD)
CALL LOAD (ILUNFI, PVM1,                 YDD=YLD)
CALL LOAD (ILUNFI, PLITOT,               YDD=YLD)
CALL LOAD (ILUNFI, PVERVEL,              YDD=YLD)
CALL LOAD (ILUNFI, PQHFL,                YDD=YLD)
CALL LOAD (ILUNFI, PAHFS,                YDD=YLD)
CALL LOAD (ILUNFI, PAPHM1,               YDD=YLD)
CALL LOAD (ILUNFI, PAP,                  YDD=YLD)
CALL LOAD (ILUNFI, PAPH,                 YDD=YLD)
CALL LOAD (ILUNFI, PGEO,                 YDD=YLD)
CALL LOAD (ILUNFI, PGEOH,                YDD=YLD)
CALL LOAD (ILUNFI, PGAW,                 YDD=YLD)
CALL LOAD (ILUNFI, PCUCONVCA,            YDD=YLD)
CALL LOAD (ILUNFI, PGP2DSPP,             YDD=YLD)
CALL LOAD (ILUNFI, PTENT,                YDD=YLD)
CALL LOAD (ILUNFI, PTENQ,                YDD=YLD)
CALL LOAD (ILUNFI, PTENU,                YDD=YLD)
CALL LOAD (ILUNFI, PTENV,                YDD=YLD)
CALL LOAD (ILUNFI, PTENTA,               YDD=YLD)
CALL LOAD (ILUNFI, PTENQA,               YDD=YLD)
CALL LOAD (ILUNFI, PARPRC,               YDD=YLD)
CALL LOAD (ILUNFI, KTOPC,                YDD=YLD)
CALL LOAD (ILUNFI, KBASEC,               YDD=YLD)
CALL LOAD (ILUNFI, KTYPE,                YDD=YLD)
CALL LOAD (ILUNFI, KCBOT,                YDD=YLD)
CALL LOAD (ILUNFI, KCTOP,                YDD=YLD)
CALL LOAD (ILUNFI, KBOTSC,               YDD=YLD)
CALL LOAD (ILUNFI, LDCUM,                YDD=YLD)
CALL LOAD (ILUNFI, LDSC,                 YDD=YLD)
CALL LOAD (ILUNFI, KCBOT_LIG,            YDD=YLD)
CALL LOAD (ILUNFI, KCTOP_LIG,            YDD=YLD)
CALL LOAD (ILUNFI, LDCUM_LIG,            YDD=YLD)
CALL LOAD (ILUNFI, LDSHCV,               YDD=YLD)
CALL LOAD (ILUNFI, PLCRIT_AER,           YDD=YLD)
CALL LOAD (ILUNFI, PLU,                  YDD=YLD)
CALL LOAD (ILUNFI, PLUDE,                YDD=YLD)
CALL LOAD (ILUNFI, PLUDELI,              YDD=YLD)
CALL LOAD (ILUNFI, PSNDE,                YDD=YLD)
CALL LOAD (ILUNFI, PMFU,                 YDD=YLD)
CALL LOAD (ILUNFI, PMFD,                 YDD=YLD)
CALL LOAD (ILUNFI, PLGLAC,               YDD=YLD)
CALL LOAD (ILUNFI, PDIFCQ,               YDD=YLD)
CALL LOAD (ILUNFI, PDIFCS,               YDD=YLD)
CALL LOAD (ILUNFI, PFHPCL,               YDD=YLD)
CALL LOAD (ILUNFI, PFHPCN,               YDD=YLD)
CALL LOAD (ILUNFI, PFPLCL,               YDD=YLD)
CALL LOAD (ILUNFI, PFPLCN,               YDD=YLD)
CALL LOAD (ILUNFI, PLRAIN,               YDD=YLD)
CALL LOAD (ILUNFI, PRSUD,                YDD=YLD)
CALL LOAD (ILUNFI, PSTRCU,               YDD=YLD)
CALL LOAD (ILUNFI, PSTRCV,               YDD=YLD)
CALL LOAD (ILUNFI, PFCQLF,               YDD=YLD)
CALL LOAD (ILUNFI, PFCQIF,               YDD=YLD)
CALL LOAD (ILUNFI, PMFUDE_RATE,          YDD=YLD)
CALL LOAD (ILUNFI, PMFDDE_RATE,          YDD=YLD)
CALL LOAD (ILUNFI, PCAPE,                YDD=YLD)
CALL LOAD (ILUNFI, PWU,                  YDD=YLD)
CALL LOAD (ILUNFI, PWMEAN,               YDD=YLD)
CALL LOAD (ILUNFI, PVDISCU,              YDD=YLD)
CALL LOAD (ILUNFI, PDISS,                YDD=YLD)
CALL LOAD (ILUNCI, KTRAC)
CALL LOAD (ILUNFI, PCM1,                 YDD=YLD)
CALL LOAD (ILUNFI, PTENC,                YDD=YLD)
CALL LOAD (ILUNCI, PSCAV)
CALL LOAD (ILUNCI, PSCAV0)

CLOSE (ILUNFI)
CLOSE (ILUNCI)  

END SUBROUTINE

SUBROUTINE DIFFALL
IF (LLVERBOSE) PRINT *, " DIFF..."

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')
CALL DIFF ("PTENT      ", PTENT      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENQ      ", PTENQ      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENU      ", PTENU      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENV      ", PTENV      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENTA     ", PTENTA     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENQA     ", PTENQA     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PARPRC     ", PARPRC     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KTOPC      ", KTOPC      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KBASEC     ", KBASEC     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KTYPE      ", KTYPE      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KCBOT      ", KCBOT      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KCTOP      ", KCTOP      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KBOTSC     ", KBOTSC     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("LDCUM      ", LDCUM      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("LDSC       ", LDSC       , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KCBOT_LIG  ", KCBOT_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("KCTOP_LIG  ", KCTOP_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("LDCUM_LIG  ", LDCUM_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PLU        ", PLU        , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PLUDE      ", PLUDE      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PLUDELI    ", PLUDELI    , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PSNDE      ", PSNDE      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PMFU       ", PMFU       , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PMFD       ", PMFD       , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PLGLAC     ", PLGLAC     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PDIFCQ     ", PDIFCQ     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PDIFCS     ", PDIFCS     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFHPCL     ", PFHPCL     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFHPCN     ", PFHPCN     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFPLCL     ", PFPLCL     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFPLCN     ", PFPLCN     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PLRAIN     ", PLRAIN     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PRSUD      ", PRSUD      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PSTRCU     ", PSTRCU     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PSTRCV     ", PSTRCV     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFCQLF     ", PFCQLF     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFCQIF     ", PFCQIF     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PMFUDE_RATE", PMFUDE_RATE, KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PMFDDE_RATE", PMFDDE_RATE, KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PCAPE      ", PCAPE      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PWU        ", PWU        , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PWMEAN     ", PWMEAN     , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PVDISCU    ", PVDISCU    , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PDISS      ", PDISS      , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTENC      ", PTENC      , KLUN=ILUNFO, YDD=YLD)
CLOSE (ILUNFO)

IF (LLVERBOSE) PRINT *, " ...DIFF"

END SUBROUTINE

SUBROUTINE SAVEIALL

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_OUT)//'/CUCALLN_MF.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_OUT)//'/CUCALLN_MF.IN.dat',    FORM='UNFORMATTED')

CALL SAVE (ILUNCI, PPLDARE)
CALL SAVE (ILUNCI, PPLRG)
CALL SAVE (ILUNCI, KSTEP)
CALL SAVE (ILUNCI, YDTHF)
CALL SAVE (ILUNCI, YDCST)
CALL SAVE (ILUNCI, YDERAD)
CALL SAVE (ILUNCI, YDML_PHY_SLIN)
CALL SAVE (ILUNCI, YDML_PHY_EC)
CALL SAVE (ILUNCI, YGFL)
CALL SAVE (ILUNCI, YDCHEM)
CALL SAVE (ILUNCI, YDSPP_CONFIG)
CALL SAVE (ILUNCI, YDPERTPAR)
CALL SAVE (ILUNCI, KLON)
CALL SAVE (ILUNCI, KGPBLKS)
CALL SAVE (ILUNCI, KSMAX)
CALL SAVE (ILUNCI, KLEV)
CALL SAVE (ILUNFI, PDX, KLBOUND=LBOUND (PDX))
CALL SAVE (ILUNCI, KSPPN2D)
CALL SAVE (ILUNCI, LDMCAPEA)
CALL SAVE (ILUNFI, LDLAND, KLBOUND=LBOUND (LDLAND))
CALL SAVE (ILUNCI, LDSLPHY)
CALL SAVE (ILUNCI, PTSPHY)
CALL SAVE (ILUNCI, PVDIFTS)
CALL SAVE (ILUNFI, PTM1, KLBOUND=LBOUND (PTM1))
CALL SAVE (ILUNFI, PQM1, KLBOUND=LBOUND (PQM1))
CALL SAVE (ILUNFI, PUM1, KLBOUND=LBOUND (PUM1))
CALL SAVE (ILUNFI, PVM1, KLBOUND=LBOUND (PVM1))
CALL SAVE (ILUNFI, PLITOT, KLBOUND=LBOUND (PLITOT))
CALL SAVE (ILUNFI, PVERVEL, KLBOUND=LBOUND (PVERVEL))
CALL SAVE (ILUNFI, PQHFL, KLBOUND=LBOUND (PQHFL))
CALL SAVE (ILUNFI, PAHFS, KLBOUND=LBOUND (PAHFS))
CALL SAVE (ILUNFI, PAPHM1, KLBOUND=LBOUND (PAPHM1))
CALL SAVE (ILUNFI, PAP, KLBOUND=LBOUND (PAP))
CALL SAVE (ILUNFI, PAPH, KLBOUND=LBOUND (PAPH))
CALL SAVE (ILUNFI, PGEO, KLBOUND=LBOUND (PGEO))
CALL SAVE (ILUNFI, PGEOH, KLBOUND=LBOUND (PGEOH))
CALL SAVE (ILUNFI, PGAW, KLBOUND=LBOUND (PGAW))
CALL SAVE (ILUNFI, PCUCONVCA, KLBOUND=LBOUND (PCUCONVCA))
CALL SAVE (ILUNFI, PGP2DSPP, KLBOUND=LBOUND (PGP2DSPP))
CALL SAVE (ILUNFI, PTENT, KLBOUND=LBOUND (PTENT))
CALL SAVE (ILUNFI, PTENQ, KLBOUND=LBOUND (PTENQ))
CALL SAVE (ILUNFI, PTENU, KLBOUND=LBOUND (PTENU))
CALL SAVE (ILUNFI, PTENV, KLBOUND=LBOUND (PTENV))
CALL SAVE (ILUNFI, PTENTA, KLBOUND=LBOUND (PTENTA))
CALL SAVE (ILUNFI, PTENQA, KLBOUND=LBOUND (PTENQA))
CALL SAVE (ILUNFI, PARPRC, KLBOUND=LBOUND (PARPRC))
CALL SAVE (ILUNFI, KTOPC, KLBOUND=LBOUND (KTOPC))
CALL SAVE (ILUNFI, KBASEC, KLBOUND=LBOUND (KBASEC))
CALL SAVE (ILUNFI, KTYPE, KLBOUND=LBOUND (KTYPE))
CALL SAVE (ILUNFI, KCBOT, KLBOUND=LBOUND (KCBOT))
CALL SAVE (ILUNFI, KCTOP, KLBOUND=LBOUND (KCTOP))
CALL SAVE (ILUNFI, KBOTSC, KLBOUND=LBOUND (KBOTSC))
CALL SAVE (ILUNFI, LDCUM, KLBOUND=LBOUND (LDCUM))
CALL SAVE (ILUNFI, LDSC, KLBOUND=LBOUND (LDSC))
CALL SAVE (ILUNFI, KCBOT_LIG, KLBOUND=LBOUND (KCBOT_LIG))
CALL SAVE (ILUNFI, KCTOP_LIG, KLBOUND=LBOUND (KCTOP_LIG))
CALL SAVE (ILUNFI, LDCUM_LIG, KLBOUND=LBOUND (LDCUM_LIG))
CALL SAVE (ILUNFI, LDSHCV, KLBOUND=LBOUND (LDSHCV))
CALL SAVE (ILUNFI, PLCRIT_AER, KLBOUND=LBOUND (PLCRIT_AER))
CALL SAVE (ILUNFI, PLU, KLBOUND=LBOUND (PLU))
CALL SAVE (ILUNFI, PLUDE, KLBOUND=LBOUND (PLUDE))
CALL SAVE (ILUNFI, PLUDELI, KLBOUND=LBOUND (PLUDELI))
CALL SAVE (ILUNFI, PSNDE, KLBOUND=LBOUND (PSNDE))
CALL SAVE (ILUNFI, PMFU, KLBOUND=LBOUND (PMFU))
CALL SAVE (ILUNFI, PMFD, KLBOUND=LBOUND (PMFD))
CALL SAVE (ILUNFI, PLGLAC, KLBOUND=LBOUND (PLGLAC))
CALL SAVE (ILUNFI, PDIFCQ, KLBOUND=LBOUND (PDIFCQ))
CALL SAVE (ILUNFI, PDIFCS, KLBOUND=LBOUND (PDIFCS))
CALL SAVE (ILUNFI, PFHPCL, KLBOUND=LBOUND (PFHPCL))
CALL SAVE (ILUNFI, PFHPCN, KLBOUND=LBOUND (PFHPCN))
CALL SAVE (ILUNFI, PFPLCL, KLBOUND=LBOUND (PFPLCL))
CALL SAVE (ILUNFI, PFPLCN, KLBOUND=LBOUND (PFPLCN))
CALL SAVE (ILUNFI, PLRAIN, KLBOUND=LBOUND (PLRAIN))
CALL SAVE (ILUNFI, PRSUD, KLBOUND=LBOUND (PRSUD))
CALL SAVE (ILUNFI, PSTRCU, KLBOUND=LBOUND (PSTRCU))
CALL SAVE (ILUNFI, PSTRCV, KLBOUND=LBOUND (PSTRCV))
CALL SAVE (ILUNFI, PFCQLF, KLBOUND=LBOUND (PFCQLF))
CALL SAVE (ILUNFI, PFCQIF, KLBOUND=LBOUND (PFCQIF))
CALL SAVE (ILUNFI, PMFUDE_RATE, KLBOUND=LBOUND (PMFUDE_RATE))
CALL SAVE (ILUNFI, PMFDDE_RATE, KLBOUND=LBOUND (PMFDDE_RATE))
CALL SAVE (ILUNFI, PCAPE, KLBOUND=LBOUND (PCAPE))
CALL SAVE (ILUNFI, PWU, KLBOUND=LBOUND (PWU))
CALL SAVE (ILUNFI, PWMEAN, KLBOUND=LBOUND (PWMEAN))
CALL SAVE (ILUNFI, PVDISCU, KLBOUND=LBOUND (PVDISCU))
CALL SAVE (ILUNFI, PDISS, KLBOUND=LBOUND (PDISS))
CALL SAVE (ILUNCI, KTRAC)
CALL SAVE (ILUNFI, PCM1, KLBOUND=LBOUND (PCM1))
CALL SAVE (ILUNFI, PTENC, KLBOUND=LBOUND (PTENC))
CALL SAVE (ILUNCI, PSCAV, KLBOUND=LBOUND (PSCAV))
CALL SAVE (ILUNCI, PSCAV0, KLBOUND=LBOUND (PSCAV0))

CLOSE (ILUNFI)
CLOSE (ILUNCI)  

END SUBROUTINE

SUBROUTINE SAVEOALL

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_OUT)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')
CALL SAVE (ILUNFO, PTENT, KLBOUND=LBOUND (PTENT))
CALL SAVE (ILUNFO, PTENQ, KLBOUND=LBOUND (PTENQ))
CALL SAVE (ILUNFO, PTENU, KLBOUND=LBOUND (PTENU))
CALL SAVE (ILUNFO, PTENV, KLBOUND=LBOUND (PTENV))
CALL SAVE (ILUNFO, PTENTA, KLBOUND=LBOUND (PTENTA))
CALL SAVE (ILUNFO, PTENQA, KLBOUND=LBOUND (PTENQA))
CALL SAVE (ILUNFO, PARPRC, KLBOUND=LBOUND (PARPRC))
CALL SAVE (ILUNFO, KTOPC, KLBOUND=LBOUND (KTOPC))
CALL SAVE (ILUNFO, KBASEC, KLBOUND=LBOUND (KBASEC))
CALL SAVE (ILUNFO, KTYPE, KLBOUND=LBOUND (KTYPE))
CALL SAVE (ILUNFO, KCBOT, KLBOUND=LBOUND (KCBOT))
CALL SAVE (ILUNFO, KCTOP, KLBOUND=LBOUND (KCTOP))
CALL SAVE (ILUNFO, KBOTSC, KLBOUND=LBOUND (KBOTSC))
CALL SAVE (ILUNFO, LDCUM, KLBOUND=LBOUND (LDCUM))
CALL SAVE (ILUNFO, LDSC, KLBOUND=LBOUND (LDSC))
CALL SAVE (ILUNFO, KCBOT_LIG, KLBOUND=LBOUND (KCBOT_LIG))
CALL SAVE (ILUNFO, KCTOP_LIG, KLBOUND=LBOUND (KCTOP_LIG))
CALL SAVE (ILUNFO, LDCUM_LIG, KLBOUND=LBOUND (LDCUM_LIG))
CALL SAVE (ILUNFO, PLU, KLBOUND=LBOUND (PLU))
CALL SAVE (ILUNFO, PLUDE, KLBOUND=LBOUND (PLUDE))
CALL SAVE (ILUNFO, PLUDELI, KLBOUND=LBOUND (PLUDELI))
CALL SAVE (ILUNFO, PSNDE, KLBOUND=LBOUND (PSNDE))
CALL SAVE (ILUNFO, PMFU, KLBOUND=LBOUND (PMFU))
CALL SAVE (ILUNFO, PMFD, KLBOUND=LBOUND (PMFD))
CALL SAVE (ILUNFO, PLGLAC, KLBOUND=LBOUND (PLGLAC))
CALL SAVE (ILUNFO, PDIFCQ, KLBOUND=LBOUND (PDIFCQ))
CALL SAVE (ILUNFO, PDIFCS, KLBOUND=LBOUND (PDIFCS))
CALL SAVE (ILUNFO, PFHPCL, KLBOUND=LBOUND (PFHPCL))
CALL SAVE (ILUNFO, PFHPCN, KLBOUND=LBOUND (PFHPCN))
CALL SAVE (ILUNFO, PFPLCL, KLBOUND=LBOUND (PFPLCL))
CALL SAVE (ILUNFO, PFPLCN, KLBOUND=LBOUND (PFPLCN))
CALL SAVE (ILUNFO, PLRAIN, KLBOUND=LBOUND (PLRAIN))
CALL SAVE (ILUNFO, PRSUD, KLBOUND=LBOUND (PRSUD))
CALL SAVE (ILUNFO, PSTRCU, KLBOUND=LBOUND (PSTRCU))
CALL SAVE (ILUNFO, PSTRCV, KLBOUND=LBOUND (PSTRCV))
CALL SAVE (ILUNFO, PFCQLF, KLBOUND=LBOUND (PFCQLF))
CALL SAVE (ILUNFO, PFCQIF, KLBOUND=LBOUND (PFCQIF))
CALL SAVE (ILUNFO, PMFUDE_RATE, KLBOUND=LBOUND (PMFUDE_RATE))
CALL SAVE (ILUNFO, PMFDDE_RATE, KLBOUND=LBOUND (PMFDDE_RATE))
CALL SAVE (ILUNFO, PCAPE, KLBOUND=LBOUND (PCAPE))
CALL SAVE (ILUNFO, PWU, KLBOUND=LBOUND (PWU))
CALL SAVE (ILUNFO, PWMEAN, KLBOUND=LBOUND (PWMEAN))
CALL SAVE (ILUNFO, PVDISCU, KLBOUND=LBOUND (PVDISCU))
CALL SAVE (ILUNFO, PDISS, KLBOUND=LBOUND (PDISS))
CALL SAVE (ILUNFO, PTENC, KLBOUND=LBOUND (PTENC))
CLOSE (ILUNFO)

END SUBROUTINE

SUBROUTINE COPY_RESET

PDX(:,:) = PDX_INI(:,:)
LDLAND(:,:) = LDLAND_INI(:,:)
PTM1(:,:,:) = PTM1_INI(:,:,:)
PQM1(:,:,:) = PQM1_INI(:,:,:)
PUM1(:,:,:) = PUM1_INI(:,:,:)
PVM1(:,:,:) = PVM1_INI(:,:,:)
PLITOT(:,:,:) = PLITOT_INI(:,:,:)
PVERVEL(:,:,:) = PVERVEL_INI(:,:,:)
PQHFL(:,:,:) = PQHFL_INI(:,:,:)
PAHFS(:,:,:) = PAHFS_INI(:,:,:)
PAPHM1(:,:,:) = PAPHM1_INI(:,:,:)
PAP(:,:,:) = PAP_INI(:,:,:)
PAPH(:,:,:) = PAPH_INI(:,:,:)
PGEO(:,:,:) = PGEO_INI(:,:,:)
PGEOH(:,:,:) = PGEOH_INI(:,:,:)
PGAW(:,:) = PGAW_INI(:,:)
PCUCONVCA(:,:) = PCUCONVCA_INI(:,:)
PGP2DSPP(:,:,:) = PGP2DSPP_INI(:,:,:)
PTENT(:,:,:) = PTENT_INI(:,:,:)
PTENQ(:,:,:) = PTENQ_INI(:,:,:)
PTENU(:,:,:) = PTENU_INI(:,:,:)
PTENV(:,:,:) = PTENV_INI(:,:,:)
PTENTA(:,:,:) = PTENTA_INI(:,:,:)
PTENQA(:,:,:) = PTENQA_INI(:,:,:)
PARPRC(:,:) = PARPRC_INI(:,:)
KTOPC(:,:) = KTOPC_INI(:,:)
KBASEC(:,:) = KBASEC_INI(:,:)
KTYPE(:,:) = KTYPE_INI(:,:)
KCBOT(:,:) = KCBOT_INI(:,:)
KCTOP(:,:) = KCTOP_INI(:,:)
KBOTSC(:,:) = KBOTSC_INI(:,:)
LDCUM(:,:) = LDCUM_INI(:,:)
LDSC(:,:) = LDSC_INI(:,:)
KCBOT(:,:) = KCBOT_LIG_INI(:,:)
KCTOP(:,:) = KCTOP_LIG_INI(:,:)
LDCUM(:,:) = LDCUM_LIG_INI(:,:)
LDSHCV(:,:) = LDSHCV_INI(:,:)
PLCRIT_AER(:,:,:) = PLCRIT_AER_INI(:,:,:)
PLU(:,:,:) = PLU_INI(:,:,:)
PLUDE(:,:,:) = PLUDE_INI(:,:,:)
PLUDELI = PLUDELI_INI
PSNDE(:,:,:,:) = PSNDE_INI(:,:,:,:)
PMFU(:,:,:) = PMFU_INI(:,:,:)
PMFD(:,:,:) = PMFD_INI(:,:,:)
PLGLAC(:,:,:) = PLGLAC_INI(:,:,:)
PDIFCQ(:,:,:) = PDIFCQ_INI(:,:,:)
PDIFCS(:,:,:) = PDIFCS_INI(:,:,:)
PFHPCL(:,:,:) = PFHPCL_INI(:,:,:)
PFHPCN(:,:,:) = PFHPCN_INI(:,:,:)
PFPLCL(:,:,:) = PFPLCL_INI(:,:,:)
PFPLCN(:,:,:) = PFPLCN_INI(:,:,:)
PLRAIN(:,:,:) = PLRAIN_INI(:,:,:)
PRSUD(:,:,:,:) = PRSUD_INI(:,:,:,:)
PSTRCU(:,:,:) = PSTRCU_INI(:,:,:)
PSTRCV(:,:,:) = PSTRCV_INI(:,:,:)
PFCQLF(:,:,:) = PFCQLF_INI(:,:,:)
PFCQIF(:,:,:) = PFCQIF_INI(:,:,:)
PMFUDE_RATE(:,:,:) = PMFUDE_RATE_INI(:,:,:)
PMFDDE_RATE(:,:,:) = PMFDDE_RATE_INI(:,:,:)
PCAPE(:,:) = PCAPE_INI(:,:)
PWU_INI(:,:,:) = PWU(:,:,:)
PWMEAN(:,:) = PWMEAN_INI(:,:)
PVDISCU(:,:) = PVDISCU_INI(:,:)
PDISS(:,:,:) = PDISS_INI(:,:,:)
PCM1(:,:,:,:) = PCM1_INI(:,:,:,:)
PTENC(:,:,:,:) = PTENC_INI(:,:,:,:)
PSCAV(:)  = PSCAV_INI(:)
PSCAV0(:)  = PSCAV0_INI(:)

!$ACC UPDATE DEVICE (PDX, LDLAND, PTM1, PQM1, PUM1, PVM1, PLITOT, PVERVEL, PQHFL, PAHFS, PAPHM1, PAP, PAPH, PGEO, PGEOH, &
!$ACC&           PGAW, PCUCONVCA, PGP2DSPP, PTENT, PTENQ, PTENU, PTENV, PTENTA, PTENQA, PARPRC, KTOPC, KBASEC, KTYPE, &
!$ACC&           KCBOT, KCTOP, KBOTSC, LDCUM, LDSC, KCBOT_LIG, KCTOP_LIG, LDCUM_LIG, LDSHCV, PLCRIT_AER, PLU, PLUDE, &
!$ACC&           PLUDELI, PSNDE, PMFU, PMFD, PLGLAC, PDIFCQ, PDIFCS, PFHPCL, PFHPCN, PFPLCL, PFPLCN, PLRAIN, PRSUD, &
!$ACC&           PSTRCU, PSTRCV, PFCQLF, PFCQIF, PMFUDE_RATE, PMFDDE_RATE, PCAPE, PWU, PWMEAN, PVDISCU, PDISS, PCM1, &
!$ACC&           PTENC, PSCAV, PSCAV0) IF (TRIM (CLMETHOD) == 'openaccsinglecolumn')

END SUBROUTINE

SUBROUTINE COPY_INI
  CALL ALLOC(PDX_INI,PDX)
  CALL ALLOC(LDLAND_INI,LDLAND)
  CALL ALLOC(PTM1_INI,PTM1)
  CALL ALLOC(PQM1_INI,PQM1)
  CALL ALLOC(PUM1_INI,PUM1)
  CALL ALLOC(PVM1_INI,PVM1)
  CALL ALLOC(PLITOT_INI,PLITOT)
  CALL ALLOC(PVERVEL_INI,PVERVEL)
  CALL ALLOC(PQHFL_INI,PQHFL)
  CALL ALLOC(PAHFS_INI,PAHFS)
  CALL ALLOC(PAPHM1_INI,PAPHM1)
  CALL ALLOC(PAP_INI,PAP)
  CALL ALLOC(PAPH_INI,PAPH)
  CALL ALLOC(PGEO_INI,PGEO)
  CALL ALLOC(PGEOH_INI,PGEOH)
  CALL ALLOC(PGAW_INI,PGAW)
  CALL ALLOC(PCUCONVCA_INI,PCUCONVCA)
  CALL ALLOC(PGP2DSPP_INI,PGP2DSPP)
  CALL ALLOC(PTENT_INI,PTENT)
  CALL ALLOC(PTENQ_INI,PTENQ)
  CALL ALLOC(PTENU_INI,PTENU)
  CALL ALLOC(PTENV_INI,PTENV)
  CALL ALLOC(PTENTA_INI,PTENTA)
  CALL ALLOC(PTENQA_INI,PTENQA)
  CALL ALLOC(PARPRC_INI,PARPRC)
  CALL ALLOC(KTOPC_INI,KTOPC)
  CALL ALLOC(KBASEC_INI,KBASEC)
  CALL ALLOC(KTYPE_INI,KTYPE)
  CALL ALLOC(KCBOT_INI,KCBOT)
  CALL ALLOC(KCTOP_INI,KCTOP)
  CALL ALLOC(KBOTSC_INI,KBOTSC)
  CALL ALLOC(LDCUM_INI,LDCUM)
  CALL ALLOC(LDSC_INI,LDSC)
  CALL ALLOC(KCBOT_LIG_INI,KCBOT_LIG)
  CALL ALLOC(KCTOP_LIG_INI,KCTOP_LIG)
  CALL ALLOC(LDCUM_LIG_INI,LDCUM_LIG)
  CALL ALLOC(LDSHCV_INI,LDSHCV)
  CALL ALLOC(PLCRIT_AER_INI,PLCRIT_AER)
  CALL ALLOC(PLU_INI,PLU)
  CALL ALLOC(PLUDE_INI,PLUDE)
  CALL ALLOC(PLUDELI_INI,PLUDELI)
  CALL ALLOC(PSNDE_INI,PSNDE)
  CALL ALLOC(PMFU_INI,PMFU)
  CALL ALLOC(PMFD_INI,PMFD)
  CALL ALLOC(PLGLAC_INI,PLGLAC)
  CALL ALLOC(PDIFCQ_INI,PDIFCQ)
  CALL ALLOC(PDIFCS_INI,PDIFCS)
  CALL ALLOC(PFHPCL_INI,PFHPCL)
  CALL ALLOC(PFHPCN_INI,PFHPCN)
  CALL ALLOC(PFPLCL_INI,PFPLCL)
  CALL ALLOC(PFPLCN_INI,PFPLCN)
  CALL ALLOC(PLRAIN_INI,PLRAIN)
  CALL ALLOC(PRSUD_INI,PRSUD)
  CALL ALLOC(PSTRCU_INI,PSTRCU)
  CALL ALLOC(PSTRCV_INI,PSTRCV)
  CALL ALLOC(PFCQLF_INI,PFCQLF)
  CALL ALLOC(PFCQIF_INI,PFCQIF)
  CALL ALLOC(PMFUDE_RATE_INI,PMFUDE_RATE)
  CALL ALLOC(PMFDDE_RATE_INI,PMFDDE_RATE)
  CALL ALLOC(PCAPE_INI,PCAPE)
  CALL ALLOC(PWU_INI,PWU)
  CALL ALLOC(PWMEAN_INI,PWMEAN)
  CALL ALLOC(PVDISCU_INI,PVDISCU)
  CALL ALLOC(PDISS_INI,PDISS)
  CALL ALLOC(PCM1_INI,PCM1)
  CALL ALLOC(PTENC_INI,PTENC)
  CALL ALLOC(PSCAV_INI,PSCAV)
  CALL ALLOC(PSCAV0_INI,PSCAV0)
END SUBROUTINE

SUBROUTINE RMSEALL
WRITE (0, *) "**************************************" 
WRITE (0, *) "**************************************" 
WRITE (0, *) "**************************************" 

!## !$ACC UPDATE HOST (PDX, LDLAND, PTM1, PQM1, PUM1, PVM1, PLITOT, PVERVEL, PQHFL, PAHFS, PAPHM1, PAP, PAPH, PGEO, PGEOH, &
!## !$ACC&           PGAW, PCUCONVCA, PGP2DSPP, PTENT, PTENQ, PTENU, PTENV, PTENTA, PTENQA, PARPRC, KTOPC, KBASEC, KTYPE, &
!## !$ACC&           KCBOT, KCTOP, KBOTSC, LDCUM, LDSC, KCBOT_LIG, KCTOP_LIG, LDCUM_LIG, LDSHCV, PLCRIT_AER, PLU, PLUDE, &
!## !$ACC&           PLUDELI, PSNDE, PMFU, PMFD, PLGLAC, PDIFCQ, PDIFCS, PFHPCL, PFHPCN, PFPLCL, PFPLCN, PLRAIN, PRSUD, &
!## !$ACC&           PSTRCU, PSTRCV, PFCQLF, PFCQIF, PMFUDE_RATE, PMFDDE_RATE, PCAPE, PWU, PWMEAN, PVDISCU, PDISS, PCM1, &
!## !$ACC&           PTENC, PSCAV, PSCAV0) IF (TRIM (CLMETHOD) == 'openaccsinglecolumn')
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')
CALL RMSE ("PTENT      ", PTENT      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PTENQ      ", PTENQ      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PTENU      ", PTENU      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PTENV      ", PTENV      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PTENTA     ", PTENTA     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PTENQA     ", PTENQA     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PARPRC     ", PARPRC     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("KTOPC      ", KTOPC      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("KBASEC     ", KBASEC     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("KTYPE      ", KTYPE      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("KCBOT      ", KCBOT      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("KCTOP      ", KCTOP      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("KBOTSC     ", KBOTSC     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("LDCUM      ", LDCUM      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("LDSC       ", LDSC       , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("KCBOT_LIG  ", KCBOT_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("KCTOP_LIG  ", KCTOP_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("LDCUM_LIG  ", LDCUM_LIG  , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PLU        ", PLU        , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PLUDE      ", PLUDE      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PLUDELI    ", PLUDELI    , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PSNDE      ", PSNDE      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PMFU       ", PMFU       , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PMFD       ", PMFD       , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PLGLAC     ", PLGLAC     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PDIFCQ     ", PDIFCQ     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PDIFCS     ", PDIFCS     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PFHPCL     ", PFHPCL     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PFHPCN     ", PFHPCN     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PFPLCL     ", PFPLCL     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PFPLCN     ", PFPLCN     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PLRAIN     ", PLRAIN     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PRSUD      ", PRSUD      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PSTRCU     ", PSTRCU     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PSTRCV     ", PSTRCV     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PFCQLF     ", PFCQLF     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PFCQIF     ", PFCQIF     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PMFUDE_RATE", PMFUDE_RATE, KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PMFDDE_RATE", PMFDDE_RATE, KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PCAPE      ", PCAPE      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PWU        ", PWU        , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PWMEAN     ", PWMEAN     , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PVDISCU    ", PVDISCU    , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PDISS      ", PDISS      , KLUN=ILUNFO, YDD=YLD)
CALL RMSE ("PTENC      ", PTENC      , KLUN=ILUNFO, YDD=YLD)
CLOSE (ILUNFO)


END SUBROUTINE

END 
