MODULE YOMALLOC

USE PARKIND1

IMPLICIT NONE


INTERFACE ALLOC
MODULE PROCEDURE :: ALLOCLM0
MODULE PROCEDURE :: ALLOCLM1
MODULE PROCEDURE :: ALLOCLM2
MODULE PROCEDURE :: ALLOCLM3
MODULE PROCEDURE :: ALLOCLM4
MODULE PROCEDURE :: ALLOCLM5
MODULE PROCEDURE :: ALLOCRD0
MODULE PROCEDURE :: ALLOCRD1
MODULE PROCEDURE :: ALLOCRD2
MODULE PROCEDURE :: ALLOCRD3
MODULE PROCEDURE :: ALLOCRD4
MODULE PROCEDURE :: ALLOCRD5
MODULE PROCEDURE :: ALLOCRM0
MODULE PROCEDURE :: ALLOCRM1
MODULE PROCEDURE :: ALLOCRM2
MODULE PROCEDURE :: ALLOCRM3
MODULE PROCEDURE :: ALLOCRM4
MODULE PROCEDURE :: ALLOCRM5
MODULE PROCEDURE :: ALLOCIM0
MODULE PROCEDURE :: ALLOCIM1
MODULE PROCEDURE :: ALLOCIM2
MODULE PROCEDURE :: ALLOCIM3
MODULE PROCEDURE :: ALLOCIM4
MODULE PROCEDURE :: ALLOCIM5
END INTERFACE

CONTAINS




SUBROUTINE ALLOCLM0 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P
LOGICAL (KIND=JPLM), POINTER :: Z
P=Z
END SUBROUTINE




SUBROUTINE ALLOCLM1 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P(:)
LOGICAL (KIND=JPLM), POINTER :: Z(:)

INTEGER :: ILBOUND(1)
INTEGER :: IUBOUND(1)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCLM2 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P(:,:)
LOGICAL (KIND=JPLM), POINTER :: Z(:,:)

INTEGER :: ILBOUND(2)
INTEGER :: IUBOUND(2)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCLM3 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P(:,:,:)
LOGICAL (KIND=JPLM), POINTER :: Z(:,:,:)

INTEGER :: ILBOUND(3)
INTEGER :: IUBOUND(3)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCLM4 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P(:,:,:,:)
LOGICAL (KIND=JPLM), POINTER :: Z(:,:,:,:)

INTEGER :: ILBOUND(4)
INTEGER :: IUBOUND(4)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCLM5 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P(:,:,:,:,:)
LOGICAL (KIND=JPLM), POINTER :: Z(:,:,:,:,:)

INTEGER :: ILBOUND(5)
INTEGER :: IUBOUND(5)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4),ILBOUND (5):IUBOUND&
    & (5)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCRD0 (P, Z)

REAL (KIND=JPRD), POINTER :: P
REAL (KIND=JPRD), POINTER :: Z
P=Z
END SUBROUTINE




SUBROUTINE ALLOCRD1 (P, Z)

REAL (KIND=JPRD), POINTER :: P(:)
REAL (KIND=JPRD), POINTER :: Z(:)

INTEGER :: ILBOUND(1)
INTEGER :: IUBOUND(1)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCRD2 (P, Z)

REAL (KIND=JPRD), POINTER :: P(:,:)
REAL (KIND=JPRD), POINTER :: Z(:,:)

INTEGER :: ILBOUND(2)
INTEGER :: IUBOUND(2)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCRD3 (P, Z)

REAL (KIND=JPRD), POINTER :: P(:,:,:)
REAL (KIND=JPRD), POINTER :: Z(:,:,:)

INTEGER :: ILBOUND(3)
INTEGER :: IUBOUND(3)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCRD4 (P, Z)

REAL (KIND=JPRD), POINTER :: P(:,:,:,:)
REAL (KIND=JPRD), POINTER :: Z(:,:,:,:)

INTEGER :: ILBOUND(4)
INTEGER :: IUBOUND(4)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCRD5 (P, Z)

REAL (KIND=JPRD), POINTER :: P(:,:,:,:,:)
REAL (KIND=JPRD), POINTER :: Z(:,:,:,:,:)

INTEGER :: ILBOUND(5)
INTEGER :: IUBOUND(5)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4),ILBOUND (5):IUBOUND&
    & (5)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCRM0 (P, Z)

REAL (KIND=JPRM), POINTER :: P
REAL (KIND=JPRM), POINTER :: Z
P=Z
END SUBROUTINE




SUBROUTINE ALLOCRM1 (P, Z)

REAL (KIND=JPRM), POINTER :: P(:)
REAL (KIND=JPRM), POINTER :: Z(:)

INTEGER :: ILBOUND(1)
INTEGER :: IUBOUND(1)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCRM2 (P, Z)

REAL (KIND=JPRM), POINTER :: P(:,:)
REAL (KIND=JPRM), POINTER :: Z(:,:)

INTEGER :: ILBOUND(2)
INTEGER :: IUBOUND(2)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCRM3 (P, Z)

REAL (KIND=JPRM), POINTER :: P(:,:,:)
REAL (KIND=JPRM), POINTER :: Z(:,:,:)

INTEGER :: ILBOUND(3)
INTEGER :: IUBOUND(3)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCRM4 (P, Z)

REAL (KIND=JPRM), POINTER :: P(:,:,:,:)
REAL (KIND=JPRM), POINTER :: Z(:,:,:,:)

INTEGER :: ILBOUND(4)
INTEGER :: IUBOUND(4)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCRM5 (P, Z)

REAL (KIND=JPRM), POINTER :: P(:,:,:,:,:)
REAL (KIND=JPRM), POINTER :: Z(:,:,:,:,:)

INTEGER :: ILBOUND(5)
INTEGER :: IUBOUND(5)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4),ILBOUND (5):IUBOUND&
    & (5)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCIM0 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P
INTEGER (KIND=JPIM), POINTER :: Z
P=Z
END SUBROUTINE




SUBROUTINE ALLOCIM1 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P(:)
INTEGER (KIND=JPIM), POINTER :: Z(:)

INTEGER :: ILBOUND(1)
INTEGER :: IUBOUND(1)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCIM2 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P(:,:)
INTEGER (KIND=JPIM), POINTER :: Z(:,:)

INTEGER :: ILBOUND(2)
INTEGER :: IUBOUND(2)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCIM3 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P(:,:,:)
INTEGER (KIND=JPIM), POINTER :: Z(:,:,:)

INTEGER :: ILBOUND(3)
INTEGER :: IUBOUND(3)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCIM4 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P(:,:,:,:)
INTEGER (KIND=JPIM), POINTER :: Z(:,:,:,:)

INTEGER :: ILBOUND(4)
INTEGER :: IUBOUND(4)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4)))

P=Z

END SUBROUTINE




SUBROUTINE ALLOCIM5 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P(:,:,:,:,:)
INTEGER (KIND=JPIM), POINTER :: Z(:,:,:,:,:)

INTEGER :: ILBOUND(5)
INTEGER :: IUBOUND(5)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4),ILBOUND (5):IUBOUND&
    & (5)))

P=Z

END SUBROUTINE


END
