MODULE YOMRMSE

USE PARKIND1
USE YOMDATA

IMPLICIT NONE


INTERFACE RMSE
MODULE PROCEDURE :: RMSELM0
MODULE PROCEDURE :: RMSELM1
MODULE PROCEDURE :: RMSELM2
MODULE PROCEDURE :: RMSELM3
MODULE PROCEDURE :: RMSELM4
MODULE PROCEDURE :: RMSELM5
MODULE PROCEDURE :: RMSERD0
MODULE PROCEDURE :: RMSERD1
MODULE PROCEDURE :: RMSERD2
MODULE PROCEDURE :: RMSERD3
MODULE PROCEDURE :: RMSERD4
MODULE PROCEDURE :: RMSERD5
MODULE PROCEDURE :: RMSERM0
MODULE PROCEDURE :: RMSERM1
MODULE PROCEDURE :: RMSERM2
MODULE PROCEDURE :: RMSERM3
MODULE PROCEDURE :: RMSERM4
MODULE PROCEDURE :: RMSERM5
MODULE PROCEDURE :: RMSEIM0
MODULE PROCEDURE :: RMSEIM1
MODULE PROCEDURE :: RMSEIM2
MODULE PROCEDURE :: RMSEIM3
MODULE PROCEDURE :: RMSEIM4
MODULE PROCEDURE :: RMSEIM5
END INTERFACE

CONTAINS



SUBROUTINE RMSELM0 (CDNAME, P1, KLUN, YDD)

CHARACTER (LEN=*) :: CDNAME
LOGICAL (KIND=JPLM), INTENT (IN) :: P1
INTEGER, INTENT (IN), OPTIONAL :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
LOGICAL (KIND=JPLM) :: Z2

WRITE (0, *) 'RMSE:', CDNAME, '=', 'SCALAR' 
END SUBROUTINE




SUBROUTINE RMSELM1 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
LOGICAL (KIND=JPLM), INTENT (IN) :: P1(:)
LOGICAL (KIND=JPLM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
LOGICAL (KIND=JPLM), POINTER  :: Z2(:)
INTEGER :: I

INTEGER :: I1

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]


IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1

S = 0.0

DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1) - Z2(I1))**2       

ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSELM2 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
LOGICAL (KIND=JPLM), INTENT (IN) :: P1(:,:)
LOGICAL (KIND=JPLM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
LOGICAL (KIND=JPLM), POINTER  :: Z2(:,:)
INTEGER :: I

INTEGER :: I1,I2

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1

S = 0.0

DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2) - Z2(I1,I2))**2       

ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSELM3 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
LOGICAL (KIND=JPLM), INTENT (IN) :: P1(:,:,:)
LOGICAL (KIND=JPLM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
LOGICAL (KIND=JPLM), POINTER  :: Z2(:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1

S = 0.0

DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3) - Z2(I1,I2,I3))**2       

ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSELM4 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
LOGICAL (KIND=JPLM), INTENT (IN) :: P1(:,:,:,:)
LOGICAL (KIND=JPLM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
LOGICAL (KIND=JPLM), POINTER  :: Z2(:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1

S = 0.0

DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4) - Z2(I1,I2,I3,I4))**2       

ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSELM5 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
LOGICAL (KIND=JPLM), INTENT (IN) :: P1(:,:,:,:,:)
LOGICAL (KIND=JPLM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
LOGICAL (KIND=JPLM), POINTER  :: Z2(:,:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4,I5

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1
IF (SIZE (P1, 5) /= SIZE (Z2, 5)) STOP 1

S = 0.0

DO I5 = 1, SIZE (P1, 5)
DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4,I5) - Z2(I1,I2,I3,I4,I5))**2       

ENDDO
ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE



SUBROUTINE RMSERD0 (CDNAME, P1, KLUN, YDD)

CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRD), INTENT (IN) :: P1
INTEGER, INTENT (IN), OPTIONAL :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRD) :: Z2

WRITE (0, *) 'RMSE:', CDNAME, '=', 'SCALAR' 
END SUBROUTINE




SUBROUTINE RMSERD1 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRD), INTENT (IN) :: P1(:)
REAL (KIND=JPRD) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRD), POINTER  :: Z2(:)
INTEGER :: I

INTEGER :: I1

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]


IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1

S = 0.0

DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1) - Z2(I1))**2       

ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSERD2 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRD), INTENT (IN) :: P1(:,:)
REAL (KIND=JPRD) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRD), POINTER  :: Z2(:,:)
INTEGER :: I

INTEGER :: I1,I2

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1

S = 0.0

DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2) - Z2(I1,I2))**2       

ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSERD3 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRD), INTENT (IN) :: P1(:,:,:)
REAL (KIND=JPRD) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRD), POINTER  :: Z2(:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1

S = 0.0

DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3) - Z2(I1,I2,I3))**2       

ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSERD4 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRD), INTENT (IN) :: P1(:,:,:,:)
REAL (KIND=JPRD) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRD), POINTER  :: Z2(:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1

S = 0.0

DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4) - Z2(I1,I2,I3,I4))**2       

ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSERD5 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRD), INTENT (IN) :: P1(:,:,:,:,:)
REAL (KIND=JPRD) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRD), POINTER  :: Z2(:,:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4,I5

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1
IF (SIZE (P1, 5) /= SIZE (Z2, 5)) STOP 1

S = 0.0

DO I5 = 1, SIZE (P1, 5)
DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4,I5) - Z2(I1,I2,I3,I4,I5))**2       

ENDDO
ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE



SUBROUTINE RMSERM0 (CDNAME, P1, KLUN, YDD)

CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRM), INTENT (IN) :: P1
INTEGER, INTENT (IN), OPTIONAL :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRM) :: Z2

WRITE (0, *) 'RMSE:', CDNAME, '=', 'SCALAR' 
END SUBROUTINE




SUBROUTINE RMSERM1 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRM), INTENT (IN) :: P1(:)
REAL (KIND=JPRM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRM), POINTER  :: Z2(:)
INTEGER :: I

INTEGER :: I1

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]


IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1

S = 0.0

DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1) - Z2(I1))**2       

ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSERM2 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRM), INTENT (IN) :: P1(:,:)
REAL (KIND=JPRM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRM), POINTER  :: Z2(:,:)
INTEGER :: I

INTEGER :: I1,I2

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1

S = 0.0

DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2) - Z2(I1,I2))**2       

ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSERM3 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRM), INTENT (IN) :: P1(:,:,:)
REAL (KIND=JPRM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRM), POINTER  :: Z2(:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1

S = 0.0

DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3) - Z2(I1,I2,I3))**2       

ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSERM4 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRM), INTENT (IN) :: P1(:,:,:,:)
REAL (KIND=JPRM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRM), POINTER  :: Z2(:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1

S = 0.0

DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4) - Z2(I1,I2,I3,I4))**2       

ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSERM5 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRM), INTENT (IN) :: P1(:,:,:,:,:)
REAL (KIND=JPRM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRM), POINTER  :: Z2(:,:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4,I5

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1
IF (SIZE (P1, 5) /= SIZE (Z2, 5)) STOP 1

S = 0.0

DO I5 = 1, SIZE (P1, 5)
DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4,I5) - Z2(I1,I2,I3,I4,I5))**2       

ENDDO
ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE



SUBROUTINE RMSEIM0 (CDNAME, P1, KLUN, YDD)

CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN) :: P1
INTEGER, INTENT (IN), OPTIONAL :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
INTEGER (KIND=JPIM) :: Z2

WRITE (0, *) 'RMSE:', CDNAME, '=', 'SCALAR' 
END SUBROUTINE




SUBROUTINE RMSEIM1 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN) :: P1(:)
INTEGER (KIND=JPIM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
INTEGER (KIND=JPIM), POINTER  :: Z2(:)
INTEGER :: I

INTEGER :: I1

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]


IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1

S = 0.0

DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1) - Z2(I1))**2       

ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSEIM2 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN) :: P1(:,:)
INTEGER (KIND=JPIM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
INTEGER (KIND=JPIM), POINTER  :: Z2(:,:)
INTEGER :: I

INTEGER :: I1,I2

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1

S = 0.0

DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2) - Z2(I1,I2))**2       

ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSEIM3 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN) :: P1(:,:,:)
INTEGER (KIND=JPIM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
INTEGER (KIND=JPIM), POINTER  :: Z2(:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1

S = 0.0

DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3) - Z2(I1,I2,I3))**2       

ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSEIM4 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN) :: P1(:,:,:,:)
INTEGER (KIND=JPIM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
INTEGER (KIND=JPIM), POINTER  :: Z2(:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1

S = 0.0

DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4) - Z2(I1,I2,I3,I4))**2       

ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE





SUBROUTINE RMSEIM5 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN) :: P1(:,:,:,:,:)
INTEGER (KIND=JPIM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
INTEGER (KIND=JPIM), POINTER  :: Z2(:,:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4,I5

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

CALL YDD%SHUFFLE (Z2)

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1
IF (SIZE (P1, 5) /= SIZE (Z2, 5)) STOP 1

S = 0.0

DO I5 = 1, SIZE (P1, 5)
DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4,I5) - Z2(I1,I2,I3,I4,I5))**2       

ENDDO
ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) 'RMSE:', CDNAME, '=', S

END SUBROUTINE


END
