SUBROUTINE GPUMEMSTAT (CDFILE, KLINE, CDMESS)

USE FIELD_STATISTICS_MODULE
USE YOMMP0, ONLY : MYPROC

IMPLICIT NONE

CHARACTER (LEN=*) :: CDFILE
INTEGER           :: KLINE
CHARACTER (LEN=*) :: CDMESS

INTEGER*8 :: ISIZE_SMI
INTEGER*8 :: ISIZE_ACC
INTEGER*8 :: IALLOCATED, IDELETED

LOGICAL, SAVE :: LLFIRST = .TRUE.

COMMON /GPUMEMCOM/ NMETADATA
INTEGER*8 :: NMETADATA
INTEGER*8, PARAMETER :: MB = 1024 * 1024

INTEGER*8 :: ISIZE (8)
CHARACTER*20 :: CLABEL (8)
CHARACTER*32 :: CLENV
CHARACTER*50 :: CLLOCATION

INTEGER :: I

CALL GETENV ('GPUMEM', CLENV)

IF (CLENV /= '1') RETURN

FIELD_STATISTICS_ENABLE = .TRUE.


IF (LLFIRST) THEN
  CLABEL (1) = "METADATA"
  CLABEL (2) = "FIELDAPI CUR"
  CLABEL (3) = "FIELDAPI MAX"
  CLABEL (4) = "TOTAL"
  CLABEL (5) = "SMI"
  CLABEL (6) = "ACC"
  CLABEL (7) = "ALLOCATED"
  CLABEL (8) = "DELETED"

  WRITE (0, '(" # GPU = ",A50)', ADVANCE='NO') "LOCATION"

  DO I = 1, 8
    WRITE (0, '(A20)', ADVANCE='NO') TRIM (CLABEL (I))
  ENDDO

  WRITE (0, '(" # ",A)') " COMMENT "

  LLFIRST = .FALSE.
ENDIF

IF (MYPROC == 1) THEN
  CALL NVIDIA_SMI (ISIZE_SMI)
ELSE
  ISIZE_SMI = 0
ENDIF

CALL NVIDIA_FREE_MEMORY (ISIZE_ACC)
CALL NVIDIA_PRESENT_DUMP (IALLOCATED, IDELETED)

ISIZE = [NMETADATA, FIELD_STATISTICS%MEMORY_DEVICE_CUR, FIELD_STATISTICS%MEMORY_DEVICE_MAX, &
      &  NMETADATA+FIELD_STATISTICS%MEMORY_DEVICE_CUR, ISIZE_SMI * MB, ISIZE_ACC,           &
      &  IALLOCATED, IDELETED]

WRITE (CLLOCATION, '(I0)') KLINE
CLLOCATION = TRIM (CDFILE)//':'//TRIM (CLLOCATION)

WRITE (0, '("   GPU = ",A50)', ADVANCE='NO') CLLOCATION

DO I = 1, 8
  WRITE (0, '(A20)', ADVANCE='NO') MEMFMT (ISIZE (I))
ENDDO

WRITE (0, '(" # ",A)') CDMESS


CONTAINS

CHARACTER*20 FUNCTION MEMFMT (KSIZE)

INTEGER*8 :: KSIZE
INTEGER*8 :: ISIZE

ISIZE = KSIZE / MB

WRITE (MEMFMT, '(I20)') ISIZE

MEMFMT = ADJUSTR (MEMFMT)

END FUNCTION

END SUBROUTINE

SUBROUTINE GPUMEMINCR (KSIZE)

IMPLICIT NONE

INTEGER*8 :: KSIZE

COMMON /GPUMEMCOM/ NMETADATA
INTEGER*8 :: NMETADATA

NMETADATA = NMETADATA + KSIZE

END SUBROUTINE

SUBROUTINE GPUMEMDECR (KSIZE)

IMPLICIT NONE

INTEGER*8 :: KSIZE

COMMON /GPUMEMCOM/ NMETADATA
INTEGER*8 :: NMETADATA

NMETADATA = NMETADATA - KSIZE

END SUBROUTINE

