MODULE STACK_MOD

USE PARKIND1, ONLY : JPRB, JPIM, JPIA
USE DEV_ALLOC_MODULE

IMPLICIT NONE

TYPE STACK_DATA
  REAL (KIND=4), POINTER :: ZDATA4 (:,:,:,:)
  REAL (KIND=8), POINTER :: ZDATA8 (:,:,:,:)
  INTEGER*8 :: IALIGN
CONTAINS
  GENERIC :: INIT  => STACK_INIT, STACK_INIT_OPTS
  PROCEDURE, PRIVATE :: STACK_INIT
  PROCEDURE, PRIVATE :: STACK_INIT_OPTS
  PROCEDURE :: FINAL => STACK_FINAL
END TYPE

TYPE STACK
  INTEGER*8 :: L4
  INTEGER*8 :: U4
  INTEGER*8 :: L8
  INTEGER*8 :: U8
END TYPE

TYPE PARALLEL_OPTS

  INTEGER(KIND=JPIM) :: ISTACKSIZE4     = 0
  CHARACTER*32       :: CLSTACKSIZE4    = ''

  INTEGER(KIND=JPIM) :: ISTACKSIZE8     = 0
  CHARACTER*32       :: CLSTACKSIZE8    = ''

  CHARACTER*3        :: CLSLCOMMACC     = ''
  CHARACTER*3        :: CLSLEXTPOLACC   = ''
  CHARACTER*3        :: CLPARALLEL      = ''
  CHARACTER*3        :: CLPERSISTENT    = ''

  CHARACTER*3        :: CLHOST              = ''
  CHARACTER*3        :: CLHOST_CPG_DRV      = ''
  CHARACTER*3        :: CLHOST_LAPINEA_DRV  = ''
  CHARACTER*3        :: CLHOST_LAPINEB_DRV  = ''
  CHARACTER*3        :: CLHOST_CPGLAG_DRV   = ''
  CHARACTER*3        :: CLLEGACY_SCAN2M     = ''
  CHARACTER*3        :: CLSPNORM            = ''

  LOGICAL            :: LLSLCOMMACC     = .FALSE.
  LOGICAL            :: LLSLEXTPOLACC   = .FALSE.
  LOGICAL            :: LLPARALLEL      = .FALSE.
  LOGICAL            :: LLPERSISTENT    = .FALSE.

  LOGICAL            :: LLHOST              = .FALSE.
  LOGICAL            :: LLHOST_CPG_DRV      = .FALSE.
  LOGICAL            :: LLHOST_LAPINEA_DRV  = .FALSE.
  LOGICAL            :: LLHOST_LAPINEB_DRV  = .FALSE.
  LOGICAL            :: LLHOST_CPGLAG_DRV   = .FALSE.
  LOGICAL            :: LLLEGACY_SCAN2M     = .FALSE.
  LOGICAL            :: LLSPNORM            = .FALSE.


  INTEGER(KIND=JPIM) :: NBLOMA          = 100000000
  CHARACTER*32       :: CLBLOMA         = ''
CONTAINS
  PROCEDURE :: INIT  => PARALLEL_OPTS_INIT
  PROCEDURE :: FINAL => PARALLEL_OPTS_FINAL
END TYPE

PRIVATE

TYPE (STACK_DATA) :: YSTACK
PUBLIC :: STACK, YSTACK, PARALLEL_OPTS

CONTAINS

SUBROUTINE STACK_INIT_OPTS (SELF, YDPARALLEL_OPTS, YDGEOMETRY)

USE GEOMETRY_MOD, ONLY : GEOMETRY

CLASS (STACK_DATA) :: SELF
TYPE (PARALLEL_OPTS), INTENT (IN) :: YDPARALLEL_OPTS
TYPE (GEOMETRY)     , INTENT (IN) :: YDGEOMETRY

INTEGER :: IGPBLKS

IGPBLKS = MIN (YDGEOMETRY%YRDIM%NGPBLKS,YDPARALLEL_OPTS%NBLOMA)

CALL SELF%INIT (YDGEOMETRY%YRDIM%NPROMA,             &
              & YDGEOMETRY%YRDIMV%NFLEVG,            &
              & IGPBLKS,                             &
              & KSIZE4=YDPARALLEL_OPTS%ISTACKSIZE4,  &
              & KSIZE8=YDPARALLEL_OPTS%ISTACKSIZE8)

END SUBROUTINE

SUBROUTINE STACK_INIT (SELF, KPROMA, KFLEVG, KGPBLKS, KSIZE4, KSIZE8)

CLASS (STACK_DATA) :: SELF
INTEGER (KIND=JPIM), INTENT (IN) :: KPROMA, KFLEVG, KGPBLKS
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: KSIZE4, KSIZE8

SELF%IALIGN = 8 

IF (PRESENT (KSIZE4)) THEN
IF (KSIZE4 > 0) CALL DEV_ALLOCATE_DIM (SELF%ZDATA4, UBOUNDS=[KPROMA,KFLEVG,KSIZE4,KGPBLKS], MAP_DEVPTR=.TRUE.)
ENDIF

IF (PRESENT (KSIZE8)) THEN
IF (KSIZE8 > 0) CALL DEV_ALLOCATE_DIM (SELF%ZDATA8, UBOUNDS=[KPROMA,KFLEVG,KSIZE8,KGPBLKS], MAP_DEVPTR=.TRUE.)
ENDIF

!$acc enter data create (SELF)
!$acc update device (SELF)

IF (ASSOCIATED (SELF%ZDATA4)) THEN
!$acc enter data attach (SELF%ZDATA4)
ENDIF

IF (ASSOCIATED (SELF%ZDATA8)) THEN
!$acc enter data attach (SELF%ZDATA8)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_FINAL (SELF)

CLASS (STACK_DATA) :: SELF

IF (ASSOCIATED (SELF%ZDATA4)) THEN
  !$acc exit data detach (SELF%ZDATA4)
  CALL DEV_DEALLOCATE (SELF%ZDATA4, MAP_DEVPTR=.TRUE.)
ENDIF

IF (ASSOCIATED (SELF%ZDATA8)) THEN
  !$acc exit data detach (SELF%ZDATA8)
  CALL DEV_DEALLOCATE (SELF%ZDATA8, MAP_DEVPTR=.TRUE.)
ENDIF

!$acc exit data delete (SELF)

END SUBROUTINE

SUBROUTINE PARALLEL_OPTS_INIT (SELF)

USE YOMLUN , ONLY : NULOUT

CLASS (PARALLEL_OPTS) :: SELF

CALL GETIVAR ('CLSTACKSIZE4'      , SELF%CLSTACKSIZE4      , SELF%ISTACKSIZE4                             )
CALL GETIVAR ('CLSTACKSIZE8'      , SELF%CLSTACKSIZE8      , SELF%ISTACKSIZE8                             )
CALL GETIVAR ('CLBLOMA'           , SELF%CLBLOMA           , SELF%NBLOMA                                  )
CALL GETLVAR ('PARALLEL'          , SELF%CLPARALLEL        , SELF%LLPARALLEL                              )
CALL GETLVAR ('PERSISTENT'        , SELF%CLPERSISTENT      , SELF%LLPERSISTENT      , SELF%LLPARALLEL     )
CALL GETLVAR ('SLCOMMACC'         , SELF%CLSLCOMMACC       , SELF%LLSLCOMMACC                             )
CALL GETLVAR ('SLEXTPOLACC'       , SELF%CLSLEXTPOLACC     , SELF%LLSLEXTPOLACC                           )
CALL GETLVAR ('CLHOST'            , SELF%CLHOST            , SELF%LLHOST                                  )
CALL GETLVAR ('CLHOST_CPG_DRV'    , SELF%CLHOST_CPG_DRV    , SELF%LLHOST_CPG_DRV    , SELF%LLHOST         )
CALL GETLVAR ('CLHOST_LAPINEA_DRV', SELF%CLHOST_LAPINEA_DRV, SELF%LLHOST_LAPINEA_DRV, SELF%LLHOST         )
CALL GETLVAR ('CLHOST_LAPINEB_DRV', SELF%CLHOST_LAPINEB_DRV, SELF%LLHOST_LAPINEB_DRV, SELF%LLHOST         )
CALL GETLVAR ('CLHOST_CPGLAG_DRV' , SELF%CLHOST_CPGLAG_DRV , SELF%LLHOST_CPGLAG_DRV , SELF%LLHOST         )
CALL GETLVAR ('CLLEGACY_SCAN2M'   , SELF%CLLEGACY_SCAN2M   , SELF%LLLEGACY_SCAN2M                         )
CALL GETLVAR ('CLSPNORM'          , SELF%CLSPNORM          , SELF%LLSPNORM          , SELF%LLLEGACY_SCAN2M)

CONTAINS

SUBROUTINE GETIVAR (CDNAME, CDVALUE, KVALUE)

CHARACTER (LEN=*),   INTENT (IN)    :: CDNAME
CHARACTER (LEN=*),   INTENT (INOUT) :: CDVALUE
INTEGER (KIND=JPIM), INTENT (INOUT) :: KVALUE

CHARACTER*20 :: CLNAME

CDVALUE = ''

CALL GETENV (TRIM (CDNAME), CDVALUE)

IF (TRIM (CDVALUE) /= '') THEN
  READ (CDVALUE, *) KVALUE
ENDIF

CLNAME = CDNAME

WRITE (NULOUT, '(A20," = ",I0)') CLNAME, KVALUE

END SUBROUTINE

SUBROUTINE GETLVAR (CDNAME, CDVALUE, LDVALUE, LDDEFAULT)

CHARACTER (LEN=*),   INTENT (IN)    :: CDNAME
CHARACTER (LEN=*),   INTENT (INOUT) :: CDVALUE
LOGICAL,             INTENT (INOUT) :: LDVALUE
LOGICAL, OPTIONAL,   INTENT (INOUT) :: LDDEFAULT

CHARACTER*20 :: CLNAME

CDVALUE = ''

CALL GETENV (TRIM (CDNAME), CDVALUE)

IF (TRIM (CDVALUE) /= '' .AND. TRIM (CDVALUE) /= '0') THEN
  LDVALUE = .TRUE.
ELSEIF (PRESENT (LDDEFAULT)) THEN
  LDVALUE = LDDEFAULT
ENDIF

CLNAME = CDNAME

WRITE (NULOUT, '(A20," = ",L1)') CLNAME, LDVALUE

END SUBROUTINE

END SUBROUTINE

SUBROUTINE PARALLEL_OPTS_FINAL (SELF)

CLASS (PARALLEL_OPTS) :: SELF

END SUBROUTINE

END MODULE

