MODULE YOMDBG



USE PARKIND1
USE IEEE_ARITHMETIC, ONLY : ISNAN => IEEE_IS_NAN
#ifdef _OPENACC
USE OPENACC, ONLY : ACC_IS_PRESENT
#endif

IMPLICIT NONE

LOGICAL :: LLDBG = .FALSE.
LOGICAL :: LLFALSE = .FALSE.


INTEGER :: IBLOCK
!$OMP THREADPRIVATE (IBLOCK)

#ifdef UNDEF
INTERFACE PNNN
  MODULE PROCEDURE :: PNNN1, PNNN2
END INTERFACE
#endif

INTERFACE PCRC
  MODULE PROCEDURE :: PCRC1, PCRC2, PCRC3, PCRC4, PCRCI3, PCRCL1, PCRCL2, PCRCI1, PCRCI2
END INTERFACE

INTERFACE PCRCPROM
  MODULE PROCEDURE :: PCRCPROM2, PCRCPROM3, PCRCPROM4, PCRCPROMI4
END INTERFACE 

INTERFACE PVAL
  MODULE PROCEDURE :: PVAL1, PVAL2, PVAL3
END INTERFACE

INTEGER, PRIVATE :: NGPBLKS, NGPTOT

REAL(KIND=JPRB), POINTER :: ZPB1 (:,:)
REAL(KIND=JPRB), POINTER :: ZPB2 (:,:,:)
REAL(KIND=JPRB), POINTER :: ZPGMV (:,:,:,:)
REAL(KIND=JPRB), POINTER :: ZPGMVT1 (:,:,:,:)
REAL(KIND=JPRB), POINTER :: ZPGFL (:,:,:,:)
REAL(KIND=JPRB), POINTER :: ZPGFLT1 (:,:,:,:)

CONTAINS

SUBROUTINE PP (CDFILE, KLINE, CDMESS)

USE MPL_BARRIER_MOD

CHARACTER (LEN=*), INTENT (IN) :: CDFILE, CDMESS
INTEGER (KIND=JPIM), INTENT (IN) :: KLINE

WRITE (0, *) __FILE__, ':', __LINE__, " ZPB1    = ", LOC (ZPB1    (1,1)    )
WRITE (0, *) __FILE__, ':', __LINE__, " ZPB2    = ", LOC (ZPB2    (1,1,1)  )
WRITE (0, *) __FILE__, ':', __LINE__, " ZPGMV   = ", LOC (ZPGMV   (1,1,1,1))
WRITE (0, *) __FILE__, ':', __LINE__, " ZPGMVT1 = ", LOC (ZPGMVT1 (1,1,1,1))
WRITE (0, *) __FILE__, ':', __LINE__, " ZPGFL   = ", LOC (ZPGFL   (1,1,1,1))
WRITE (0, *) __FILE__, ':', __LINE__, " ZPGFLT1 = ", LOC (ZPGFLT1 (1,1,1,1))

WRITE (0, *) __FILE__, ':', __LINE__, " ZPB1    = ", UBOUND (ZPB1   )
WRITE (0, *) __FILE__, ':', __LINE__, " ZPB2    = ", UBOUND (ZPB2   )
WRITE (0, *) __FILE__, ':', __LINE__, " ZPGMV   = ", UBOUND (ZPGMV  )
WRITE (0, *) __FILE__, ':', __LINE__, " ZPGMVT1 = ", UBOUND (ZPGMVT1)
WRITE (0, *) __FILE__, ':', __LINE__, " ZPGFL   = ", UBOUND (ZPGFL  )
WRITE (0, *) __FILE__, ':', __LINE__, " ZPGFLT1 = ", UBOUND (ZPGFLT1)


WRITE (0, *) __FILE__, ':', __LINE__ 
CALL FLUSH (0)

CALL PCRC (CDFILE, KLINE, ZPB1, "ZPB1")
CALL PCRC (CDFILE, KLINE, ZPB2, "ZPB2")
CALL PCRC (CDFILE, KLINE, ZPGMV, "ZPGMV")
CALL PCRC (CDFILE, KLINE, ZPGMVT1, "ZPGMVT1")
CALL PCRC (CDFILE, KLINE, ZPGFL, "ZPGFL")
CALL PCRC (CDFILE, KLINE, ZPGFLT1, "ZPGFLT1")

WRITE (0, *) __FILE__, ':', __LINE__ 

CALL MPL_BARRIER ()

END SUBROUTINE

SUBROUTINE PVAL1 (CDFILE, KLINE, P1, CDMESS)

CHARACTER (LEN=*), INTENT (IN) :: CDFILE, CDMESS
INTEGER (KIND=JPIM), INTENT (IN) :: KLINE
REAL (KIND=JPRB), INTENT (IN) :: P1 (:)


WRITE (*, '(10E30.20)') P1 (1:10)

END SUBROUTINE

SUBROUTINE PVAL2 (CDFILE, KLINE, P2, CDMESS)

CHARACTER (LEN=*), INTENT (IN) :: CDFILE, CDMESS
INTEGER (KIND=JPIM), INTENT (IN) :: KLINE
REAL (KIND=JPRB), INTENT (IN) :: P2 (:,:)


WRITE (*, '(10E30.20)') P2 (1:10,1)

END SUBROUTINE

SUBROUTINE PVAL3 (CDFILE, KLINE, P3, CDMESS)

CHARACTER (LEN=*), INTENT (IN) :: CDFILE, CDMESS
INTEGER (KIND=JPIM), INTENT (IN) :: KLINE
REAL (KIND=JPRB), INTENT (IN) :: P3 (:,:,:)


WRITE (*, '(10E30.20)') P3 (1:10,1,1)

END SUBROUTINE

SUBROUTINE DBG_INIT (KGPTOT, KGPBLKS)

USE YOMMP0, ONLY : MYPROC, NPROC
USE OML_MOD

INTEGER :: KGPTOT, KGPBLKS

INTEGER :: IBL, ILUN
CHARACTER*64 :: CLFILE

LOGICAL, SAVE :: LLDONE = .FALSE.

IF (LLDONE) RETURN

NGPTOT = KGPTOT
NGPBLKS = KGPBLKS

WRITE (20, *) __FILE__, ':', __LINE__ , " NGPTOT = ", NGPTOT, " NGPBLKS = ", NGPBLKS

LLDONE = .TRUE.

END SUBROUTINE

SUBROUTINE PNAN (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:)
CHARACTER (LEN=*) :: CDMESS

INTEGER :: ILUN

IF (.NOT. LLDBG) RETURN

ILUN = 0

WRITE (ILUN, '(A,":",I6.6," ",A," ",I16)') CDF, KL, CDMESS, COUNT (ISNAN (P))
CALL FLUSH (ILUN)

END SUBROUTINE

SUBROUTINE PCRCPROM2 (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:,:)
CHARACTER (LEN=*) :: CDMESS

INTEGER :: IBL, NPROMA, IE

REAL (KIND=JPRB) :: Z (NGPTOT)

Z = 0.

NPROMA = SIZE (P, 1)

DO IBL = 1, SIZE (P, 2)
  IE = MIN (IBL*NPROMA, NGPTOT) - (IBL-1)*NPROMA
  Z (1+(IBL-1)*NPROMA:MIN (IBL*NPROMA, NGPTOT)) = P (1:IE,IBL)
ENDDO

CALL PCRC (CDF, KL, Z, CDMESS)


END SUBROUTINE

SUBROUTINE PCRCPROM3 (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:,:,:)
CHARACTER (LEN=*) :: CDMESS

INTEGER :: IBL, NPROMA, IE

REAL (KIND=JPRB) :: Z (NGPTOT, SIZE (P, 2))

Z = 0.

NPROMA = SIZE (P, 1)

DO IBL = 1, SIZE (P, 3)
  IE = MIN (IBL*NPROMA, NGPTOT) - (IBL-1)*NPROMA
  Z (1+(IBL-1)*NPROMA:MIN (IBL*NPROMA, NGPTOT),:) = P (1:IE,:,IBL)
ENDDO

CALL PCRC (CDF, KL, Z, CDMESS)

END SUBROUTINE

SUBROUTINE PCRCPROMI4 (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
INTEGER (KIND=JPIM), INTENT (IN) :: P (:,:,:,:)
CHARACTER (LEN=*) :: CDMESS

INTEGER :: IBL, NPROMA, IE

INTEGER (KIND=JPIM) :: Z (NGPTOT, SIZE (P, 2), SIZE (P, 3))

Z = 0.

NPROMA = SIZE (P, 1)

DO IBL = 1, SIZE (P, 4)
  IE = MIN (IBL*NPROMA, NGPTOT) - (IBL-1)*NPROMA
  Z (1+(IBL-1)*NPROMA:MIN (IBL*NPROMA, NGPTOT),:,:) = P (1:IE,:,:,IBL)
ENDDO

CALL PCRC (CDF, KL, Z, CDMESS)

END SUBROUTINE

SUBROUTINE PCRCPROM4 (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:,:,:,:)
CHARACTER (LEN=*) :: CDMESS

INTEGER :: IBL, NPROMA, IE

REAL (KIND=JPRB) :: Z (NGPTOT, SIZE (P, 2), SIZE (P, 3))

Z = 0.

NPROMA = SIZE (P, 1)

DO IBL = 1, SIZE (P, 4)
  IE = MIN (IBL*NPROMA, NGPTOT) - (IBL-1)*NPROMA
  Z (1+(IBL-1)*NPROMA:MIN (IBL*NPROMA, NGPTOT),:,:) = P (1:IE,:,:,IBL)
ENDDO

CALL PCRC (CDF, KL, Z, CDMESS)

END SUBROUTINE

SUBROUTINE PCRCI1 (CDF, KL, K, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
INTEGER (KIND=JPIM), INTENT (IN) :: K (:)
CHARACTER (LEN=*) :: CDMESS

INTEGER :: ILUN
INTEGER*8 :: ICRC8, ILEN8

ILUN = 20

ICRC8 = 0
ILEN8 = SIZE (K) * KIND (K)

CALL CRC64 (K, ILEN8, ICRC8)

WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
CALL FLUSH (ILUN)

WRITE (0, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
CALL FLUSH (0)

END SUBROUTINE

SUBROUTINE PCRCI2 (CDF, KL, K, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
INTEGER (KIND=JPIM), INTENT (IN) :: K (:,:)
CHARACTER (LEN=*) :: CDMESS

INTEGER :: ILUN
INTEGER*8 :: ICRC8, ILEN8

ILUN = 20

ICRC8 = 0
ILEN8 = SIZE (K) * KIND (K)

CALL CRC64 (K, ILEN8, ICRC8)

WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
CALL FLUSH (ILUN)

WRITE (0, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
CALL FLUSH (0)

END SUBROUTINE

SUBROUTINE PCRCL1 (CDF, KL, L, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
LOGICAL, INTENT (IN) :: L (:)
CHARACTER (LEN=*) :: CDMESS

INTEGER :: ILUN
INTEGER*8 :: ICRC8, ILEN8

ILUN = 20

ICRC8 = 0
ILEN8 = SIZE (L) * KIND (L)

CALL CRC64 (L, ILEN8, ICRC8)

WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
CALL FLUSH (ILUN)

WRITE (0, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
CALL FLUSH (0)

END SUBROUTINE

SUBROUTINE PCRCL2 (CDF, KL, L, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
LOGICAL, INTENT (IN) :: L (:,:)
CHARACTER (LEN=*) :: CDMESS

INTEGER :: ILUN
INTEGER*8 :: ICRC8, ILEN8

ILUN = 20

ICRC8 = 0
ILEN8 = SIZE (L) * KIND (L)

CALL CRC64 (L, ILEN8, ICRC8)

WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
CALL FLUSH (ILUN)

WRITE (0, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
CALL FLUSH (0)

END SUBROUTINE

SUBROUTINE PCRC1 (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:)
CHARACTER (LEN=*) :: CDMESS
REAL (KIND=JPRB), ALLOCATABLE :: Z (:)

INTEGER :: ILUN
INTEGER*8 :: ICRC8, ILEN8, ICRC8_DEV
LOGICAL :: LLPRESENT

ILUN = 20

ICRC8 = 0
ILEN8 = SIZE (P) * KIND (P)

CALL CRC64 (P, ILEN8, ICRC8)

LLPRESENT = .FALSE.
#ifdef _OPENACC
LLPRESENT = ACC_IS_PRESENT (P)
#endif

IF (LLPRESENT) THEN

  ALLOCATE (Z, MOLD=P)

!$acc kernels copyout (Z)
  Z = P
!$acc end kernels

  ICRC8_DEV = 0
  CALL CRC64 (Z, ILEN8, ICRC8_DEV)

  WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16," "Z16.16," ",L1)') CDF, KL, CDMESS, ICRC8, ICRC8_DEV, ICRC8 == ICRC8_DEV
  WRITE (0,    '(A,":",I6.6," ",A," ",Z16.16," "Z16.16," ",L1)') CDF, KL, CDMESS, ICRC8, ICRC8_DEV, ICRC8 == ICRC8_DEV
ELSE
  WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
  WRITE (0,    '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
ENDIF

CALL FLUSH (ILUN)
CALL FLUSH (0)

END SUBROUTINE

SUBROUTINE PCRC2DEV (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:,:)
CHARACTER (LEN=*) :: CDMESS
REAL (KIND=JPRB), ALLOCATABLE :: Z (:,:)

INTEGER :: ILUN
INTEGER*8 :: ICRC8, ILEN8, ICRC8_DEV

ILUN = 20

ICRC8 = 0
ILEN8 = SIZE (P) * KIND (P)

ALLOCATE (Z, MOLD=P)

!$acc kernels copyout (Z) deviceptr (P)
Z = P
!$acc end kernels

ICRC8_DEV = 0

CALL CRC64 (Z, ILEN8, ICRC8_DEV)

WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8_DEV
WRITE (0,    '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8_DEV


CALL FLUSH (ILUN)
CALL FLUSH (0)

END SUBROUTINE

SUBROUTINE PCRC2 (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:,:)
CHARACTER (LEN=*) :: CDMESS
REAL (KIND=JPRB), ALLOCATABLE :: Z (:,:)

INTEGER :: ILUN
INTEGER*8 :: ICRC8, ILEN8, ICRC8_DEV
LOGICAL :: LLPRESENT

ILUN = 20

ICRC8 = 0
ILEN8 = SIZE (P) * KIND (P)

CALL CRC64 (P, ILEN8, ICRC8)

LLPRESENT = .FALSE.
#ifdef _OPENACC
LLPRESENT = ACC_IS_PRESENT (P)
#endif

IF (LLPRESENT) THEN

  ALLOCATE (Z, MOLD=P)

!$acc kernels copyout (Z)
  Z = P
!$acc end kernels

  ICRC8_DEV = 0

  CALL CRC64 (Z, ILEN8, ICRC8_DEV)

  WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16," "Z16.16," ",L1)') CDF, KL, CDMESS, ICRC8, ICRC8_DEV, ICRC8 == ICRC8_DEV
  WRITE (0,    '(A,":",I6.6," ",A," ",Z16.16," "Z16.16," ",L1)') CDF, KL, CDMESS, ICRC8, ICRC8_DEV, ICRC8 == ICRC8_DEV

ELSE
  WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
  WRITE (0,    '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
ENDIF

CALL FLUSH (ILUN)
CALL FLUSH (0)

END SUBROUTINE

SUBROUTINE PCRC3 (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:,:,:)
CHARACTER (LEN=*) :: CDMESS
REAL (KIND=JPRB), ALLOCATABLE :: Z (:,:,:)

INTEGER :: ILUN
INTEGER*8 :: ICRC8, ILEN8, ICRC8_DEV
LOGICAL :: LLPRESENT

ILUN = 20

ICRC8 = 0
ILEN8 = SIZE (P) * KIND (P)

CALL CRC64 (P, ILEN8, ICRC8)

LLPRESENT = .FALSE.
#ifdef _OPENACC
LLPRESENT = ACC_IS_PRESENT (P)
#endif

IF (LLPRESENT) THEN

  ALLOCATE (Z, MOLD=P)

!$acc kernels copyout (Z)
  Z = P
!$acc end kernels

  ICRC8_DEV = 0
  CALL CRC64 (Z, ILEN8, ICRC8_DEV)

  WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16," "Z16.16," ",L1)') CDF, KL, CDMESS, ICRC8, ICRC8_DEV, ICRC8 == ICRC8_DEV
  WRITE (0,    '(A,":",I6.6," ",A," ",Z16.16," "Z16.16," ",L1)') CDF, KL, CDMESS, ICRC8, ICRC8_DEV, ICRC8 == ICRC8_DEV

ELSE
  WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
  WRITE (0,    '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
ENDIF

CALL FLUSH (ILUN)
CALL FLUSH (0)

END SUBROUTINE

SUBROUTINE PCRC4 (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:,:,:,:)
CHARACTER (LEN=*) :: CDMESS
REAL (KIND=JPRB), ALLOCATABLE :: Z (:,:,:,:)

INTEGER :: ILUN
INTEGER*8 :: ICRC8, ILEN8, ICRC8_DEV
LOGICAL :: LLPRESENT

ILUN = 20

ICRC8 = 0
ILEN8 = SIZE (P) * KIND (P)

CALL CRC64 (P, ILEN8, ICRC8)

LLPRESENT = .FALSE.
#ifdef _OPENACC
LLPRESENT = ACC_IS_PRESENT (P)
#endif

IF (LLPRESENT) THEN

  ALLOCATE (Z, MOLD=P)

!$acc kernels copyout (Z)
  Z = P
!$acc end kernels

  ICRC8_DEV = 0
  CALL CRC64 (Z, ILEN8, ICRC8_DEV)

  WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16," "Z16.16," ",L1)') CDF, KL, CDMESS, ICRC8, ICRC8_DEV, ICRC8 == ICRC8_DEV
  WRITE (0,    '(A,":",I6.6," ",A," ",Z16.16," "Z16.16," ",L1)') CDF, KL, CDMESS, ICRC8, ICRC8_DEV, ICRC8 == ICRC8_DEV

ELSE
  WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
  WRITE (0,    '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
ENDIF

CALL FLUSH (ILUN)
CALL FLUSH (0)

END SUBROUTINE

SUBROUTINE PCRCI3 (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
INTEGER (KIND=JPIM), INTENT (IN) :: P (:,:,:)
CHARACTER (LEN=*) :: CDMESS

INTEGER :: ILUN
INTEGER*8 :: ICRC8, ILEN8

ILUN = 20

ICRC8 = 0
ILEN8 = SIZE (P) * KIND (P)

CALL CRC64 (P, ILEN8, ICRC8)

WRITE (ILUN, '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
WRITE (0,    '(A,":",I6.6," ",A," ",Z16.16)') CDF, KL, CDMESS, ICRC8
CALL FLUSH (ILUN)
CALL FLUSH (0)

END SUBROUTINE

#ifdef UNDEF

SUBROUTINE PNNN1 (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:)
CHARACTER (LEN=*) :: CDMESS
INTEGER :: J

IF (.NOT. LLDBG) RETURN

WRITE (ILUN, '(I6.6," ",I6.6," ",A,":",I6.6," ",A," NORM = ")', ADVANCE="NO") IBLOCK, ICOUNT_DBG, CDF, KL, CDMESS
WRITE (ILUN, '(E30.17," ",Z16.16)', ADVANCE='NO') SUM (ABS (P)), LOC (P (1))
WRITE (ILUN, *)

CALL FLUSH (ILUN)

ICOUNT_DBG = ICOUNT_DBG + 1

END SUBROUTINE

SUBROUTINE PNNN2 (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:,:)
CHARACTER (LEN=*) :: CDMESS
INTEGER :: J

IF (.NOT. LLDBG) RETURN

WRITE (ILUN, '(I6.6," ",I6.6," ",A,":",I6.6," ",A," NORM = ")', ADVANCE="NO") IBLOCK, ICOUNT_DBG, CDF, KL, CDMESS
WRITE (ILUN, '(E30.17," ",Z16.16)', ADVANCE='NO') SUM (ABS (P)), LOC (P (1, 1))
WRITE (ILUN, *)

CALL FLUSH (ILUN)

ICOUNT_DBG = ICOUNT_DBG + 1

END SUBROUTINE

SUBROUTINE PVVV (CDF, KL, P, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
REAL (KIND=JPRB), INTENT (IN) :: P (:)
CHARACTER (LEN=*) :: CDMESS
INTEGER :: J

IF (.NOT. LLDBG) RETURN

WRITE (ILUN, '(I6.6," ",I6.6," ",A,":",I6.6," ",A," ")', ADVANCE="NO") IBLOCK, ICOUNT_DBG, CDF, KL, CDMESS
DO J = 1, SIZE (P)
  WRITE (ILUN, '(E30.17," ")', ADVANCE='NO') P (J)
ENDDO
WRITE (ILUN, *)

CALL FLUSH (ILUN)

ICOUNT_DBG = ICOUNT_DBG + 1

END SUBROUTINE

SUBROUTINE PIIII (CDF, KL, K, CDMESS)

CHARACTER (LEN=*) :: CDF
INTEGER :: KL
INTEGER :: K
CHARACTER (LEN=*) :: CDMESS

IF (.NOT. LLDBG) RETURN

WRITE (ILUN, '(I6.6," ",I6.6," ",A,":",I6.6," ",A," ")', ADVANCE="NO") IBLOCK, ICOUNT_DBG, CDF, KL, CDMESS
WRITE (ILUN, '(I0)', ADVANCE='NO') K
WRITE (ILUN, *)

CALL FLUSH (ILUN)

ICOUNT_DBG = ICOUNT_DBG + 1

END SUBROUTINE

#endif

END MODULE

