MODULE YOMALLOC

USE PARKIND1

IMPLICIT NONE


INTERFACE ALLOC
MODULE PROCEDURE :: ALLOCLM0
MODULE PROCEDURE :: ALLOCLM1
MODULE PROCEDURE :: ALLOCLM2
MODULE PROCEDURE :: ALLOCLM3
MODULE PROCEDURE :: ALLOCLM4
MODULE PROCEDURE :: ALLOCLM5
MODULE PROCEDURE :: ALLOCRD0
MODULE PROCEDURE :: ALLOCRD1
MODULE PROCEDURE :: ALLOCRD2
MODULE PROCEDURE :: ALLOCRD3
MODULE PROCEDURE :: ALLOCRD4
MODULE PROCEDURE :: ALLOCRD5
MODULE PROCEDURE :: ALLOCRM0
MODULE PROCEDURE :: ALLOCRM1
MODULE PROCEDURE :: ALLOCRM2
MODULE PROCEDURE :: ALLOCRM3
MODULE PROCEDURE :: ALLOCRM4
MODULE PROCEDURE :: ALLOCRM5
MODULE PROCEDURE :: ALLOCIM0
MODULE PROCEDURE :: ALLOCIM1
MODULE PROCEDURE :: ALLOCIM2
MODULE PROCEDURE :: ALLOCIM3
MODULE PROCEDURE :: ALLOCIM4
MODULE PROCEDURE :: ALLOCIM5
END INTERFACE

CONTAINS




SUBROUTINE ALLOCLM0 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P
LOGICAL (KIND=JPLM), POINTER :: Z
P=Z
END SUBROUTINE




SUBROUTINE ALLOCLM1 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P(:)
LOGICAL (KIND=JPLM), POINTER :: Z(:)

INTEGER :: ILBOUND(1)
INTEGER :: IUBOUND(1)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1)))

P=Z

END SUBROUTINE

SUBROUTINE RMSELM1 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
LOGICAL (KIND=JPLM), INTENT (IN) :: P1(:)
LOGICAL (KIND=JPLM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
LOGICAL (KIND=JPLM), POINTER, INTENT (IN) :: Z2(:)
INTEGER :: I

INTEGER :: I1
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]


IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1

S = 0.0

DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1) - Z2(I1))**2       

ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCLM2 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P(:,:)
LOGICAL (KIND=JPLM), POINTER :: Z(:,:)

INTEGER :: ILBOUND(2)
INTEGER :: IUBOUND(2)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2)))

P=Z

END SUBROUTINE

SUBROUTINE RMSELM2 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
LOGICAL (KIND=JPLM), INTENT (IN) :: P1(:,:)
LOGICAL (KIND=JPLM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
LOGICAL (KIND=JPLM), POINTER, INTENT (IN) :: Z2(:,:)
INTEGER :: I

INTEGER :: I1,I2
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1

S = 0.0

DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2) - Z2(I1,I2))**2       

ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCLM3 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P(:,:,:)
LOGICAL (KIND=JPLM), POINTER :: Z(:,:,:)

INTEGER :: ILBOUND(3)
INTEGER :: IUBOUND(3)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3)))

P=Z

END SUBROUTINE

SUBROUTINE RMSELM3 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
LOGICAL (KIND=JPLM), INTENT (IN) :: P1(:,:,:)
LOGICAL (KIND=JPLM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
LOGICAL (KIND=JPLM), POINTER, INTENT (IN) :: Z2(:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1

S = 0.0

DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3) - Z2(I1,I2,I3))**2       

ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCLM4 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P(:,:,:,:)
LOGICAL (KIND=JPLM), POINTER :: Z(:,:,:,:)

INTEGER :: ILBOUND(4)
INTEGER :: IUBOUND(4)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4)))

P=Z

END SUBROUTINE

SUBROUTINE RMSELM4 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
LOGICAL (KIND=JPLM), INTENT (IN) :: P1(:,:,:,:)
LOGICAL (KIND=JPLM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
LOGICAL (KIND=JPLM), POINTER, INTENT (IN) :: Z2(:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1

S = 0.0

DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4) - Z2(I1,I2,I3,I4))**2       

ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCLM5 (P, Z)

LOGICAL (KIND=JPLM), POINTER :: P(:,:,:,:,:)
LOGICAL (KIND=JPLM), POINTER :: Z(:,:,:,:,:)

INTEGER :: ILBOUND(5)
INTEGER :: IUBOUND(5)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4),ILBOUND (5):IUBOUND&
    & (5)))

P=Z

END SUBROUTINE

SUBROUTINE RMSELM5 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
LOGICAL (KIND=JPLM), INTENT (IN) :: P1(:,:,:,:,:)
LOGICAL (KIND=JPLM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
LOGICAL (KIND=JPLM), POINTER, INTENT (IN) :: Z2(:,:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4,I5
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1
IF (SIZE (P1, 5) /= SIZE (Z2, 5)) STOP 1

S = 0.0

DO I5 = 1, SIZE (P1, 5)
DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4,I5) - Z2(I1,I2,I3,I4,I5))**2       

ENDDO
ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCRD0 (P, Z)

REAL (KIND=JPRD), POINTER :: P
REAL (KIND=JPRD), POINTER :: Z
P=Z
END SUBROUTINE




SUBROUTINE ALLOCRD1 (P, Z)

REAL (KIND=JPRD), POINTER :: P(:)
REAL (KIND=JPRD), POINTER :: Z(:)

INTEGER :: ILBOUND(1)
INTEGER :: IUBOUND(1)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1)))

P=Z

END SUBROUTINE

SUBROUTINE RMSERD1 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRD), INTENT (IN) :: P1(:)
REAL (KIND=JPRD) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRD), POINTER, INTENT (IN) :: Z2(:)
INTEGER :: I

INTEGER :: I1
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]


IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1

S = 0.0

DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1) - Z2(I1))**2       

ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCRD2 (P, Z)

REAL (KIND=JPRD), POINTER :: P(:,:)
REAL (KIND=JPRD), POINTER :: Z(:,:)

INTEGER :: ILBOUND(2)
INTEGER :: IUBOUND(2)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2)))

P=Z

END SUBROUTINE

SUBROUTINE RMSERD2 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRD), INTENT (IN) :: P1(:,:)
REAL (KIND=JPRD) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRD), POINTER, INTENT (IN) :: Z2(:,:)
INTEGER :: I

INTEGER :: I1,I2
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1

S = 0.0

DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2) - Z2(I1,I2))**2       

ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCRD3 (P, Z)

REAL (KIND=JPRD), POINTER :: P(:,:,:)
REAL (KIND=JPRD), POINTER :: Z(:,:,:)

INTEGER :: ILBOUND(3)
INTEGER :: IUBOUND(3)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3)))

P=Z

END SUBROUTINE

SUBROUTINE RMSERD3 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRD), INTENT (IN) :: P1(:,:,:)
REAL (KIND=JPRD) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRD), POINTER, INTENT (IN) :: Z2(:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1

S = 0.0

DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3) - Z2(I1,I2,I3))**2       

ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCRD4 (P, Z)

REAL (KIND=JPRD), POINTER :: P(:,:,:,:)
REAL (KIND=JPRD), POINTER :: Z(:,:,:,:)

INTEGER :: ILBOUND(4)
INTEGER :: IUBOUND(4)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4)))

P=Z

END SUBROUTINE

SUBROUTINE RMSERD4 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRD), INTENT (IN) :: P1(:,:,:,:)
REAL (KIND=JPRD) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRD), POINTER, INTENT (IN) :: Z2(:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1

S = 0.0

DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4) - Z2(I1,I2,I3,I4))**2       

ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCRD5 (P, Z)

REAL (KIND=JPRD), POINTER :: P(:,:,:,:,:)
REAL (KIND=JPRD), POINTER :: Z(:,:,:,:,:)

INTEGER :: ILBOUND(5)
INTEGER :: IUBOUND(5)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4),ILBOUND (5):IUBOUND&
    & (5)))

P=Z

END SUBROUTINE

SUBROUTINE RMSERD5 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRD), INTENT (IN) :: P1(:,:,:,:,:)
REAL (KIND=JPRD) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRD), POINTER, INTENT (IN) :: Z2(:,:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4,I5
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1
IF (SIZE (P1, 5) /= SIZE (Z2, 5)) STOP 1

S = 0.0

DO I5 = 1, SIZE (P1, 5)
DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4,I5) - Z2(I1,I2,I3,I4,I5))**2       

ENDDO
ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCRM0 (P, Z)

REAL (KIND=JPRM), POINTER :: P
REAL (KIND=JPRM), POINTER :: Z
P=Z
END SUBROUTINE




SUBROUTINE ALLOCRM1 (P, Z)

REAL (KIND=JPRM), POINTER :: P(:)
REAL (KIND=JPRM), POINTER :: Z(:)

INTEGER :: ILBOUND(1)
INTEGER :: IUBOUND(1)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1)))

P=Z

END SUBROUTINE

SUBROUTINE RMSERM1 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRM), INTENT (IN) :: P1(:)
REAL (KIND=JPRM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRM), POINTER, INTENT (IN) :: Z2(:)
INTEGER :: I

INTEGER :: I1
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]


IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1

S = 0.0

DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1) - Z2(I1))**2       

ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCRM2 (P, Z)

REAL (KIND=JPRM), POINTER :: P(:,:)
REAL (KIND=JPRM), POINTER :: Z(:,:)

INTEGER :: ILBOUND(2)
INTEGER :: IUBOUND(2)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2)))

P=Z

END SUBROUTINE

SUBROUTINE RMSERM2 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRM), INTENT (IN) :: P1(:,:)
REAL (KIND=JPRM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRM), POINTER, INTENT (IN) :: Z2(:,:)
INTEGER :: I

INTEGER :: I1,I2
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1

S = 0.0

DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2) - Z2(I1,I2))**2       

ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCRM3 (P, Z)

REAL (KIND=JPRM), POINTER :: P(:,:,:)
REAL (KIND=JPRM), POINTER :: Z(:,:,:)

INTEGER :: ILBOUND(3)
INTEGER :: IUBOUND(3)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3)))

P=Z

END SUBROUTINE

SUBROUTINE RMSERM3 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRM), INTENT (IN) :: P1(:,:,:)
REAL (KIND=JPRM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRM), POINTER, INTENT (IN) :: Z2(:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1

S = 0.0

DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3) - Z2(I1,I2,I3))**2       

ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCRM4 (P, Z)

REAL (KIND=JPRM), POINTER :: P(:,:,:,:)
REAL (KIND=JPRM), POINTER :: Z(:,:,:,:)

INTEGER :: ILBOUND(4)
INTEGER :: IUBOUND(4)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4)))

P=Z

END SUBROUTINE

SUBROUTINE RMSERM4 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRM), INTENT (IN) :: P1(:,:,:,:)
REAL (KIND=JPRM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRM), POINTER, INTENT (IN) :: Z2(:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1

S = 0.0

DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4) - Z2(I1,I2,I3,I4))**2       

ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCRM5 (P, Z)

REAL (KIND=JPRM), POINTER :: P(:,:,:,:,:)
REAL (KIND=JPRM), POINTER :: Z(:,:,:,:,:)

INTEGER :: ILBOUND(5)
INTEGER :: IUBOUND(5)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4),ILBOUND (5):IUBOUND&
    & (5)))

P=Z

END SUBROUTINE

SUBROUTINE RMSERM5 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
REAL (KIND=JPRM), INTENT (IN) :: P1(:,:,:,:,:)
REAL (KIND=JPRM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
REAL (KIND=JPRM), POINTER, INTENT (IN) :: Z2(:,:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4,I5
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1
IF (SIZE (P1, 5) /= SIZE (Z2, 5)) STOP 1

S = 0.0

DO I5 = 1, SIZE (P1, 5)
DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4,I5) - Z2(I1,I2,I3,I4,I5))**2       

ENDDO
ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCIM0 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P
INTEGER (KIND=JPIM), POINTER :: Z
P=Z
END SUBROUTINE




SUBROUTINE ALLOCIM1 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P(:)
INTEGER (KIND=JPIM), POINTER :: Z(:)

INTEGER :: ILBOUND(1)
INTEGER :: IUBOUND(1)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1)))

P=Z

END SUBROUTINE

SUBROUTINE RMSEIM1 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN) :: P1(:)
INTEGER (KIND=JPIM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
INTEGER (KIND=JPIM), POINTER, INTENT (IN) :: Z2(:)
INTEGER :: I

INTEGER :: I1
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]


IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1

S = 0.0

DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1) - Z2(I1))**2       

ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCIM2 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P(:,:)
INTEGER (KIND=JPIM), POINTER :: Z(:,:)

INTEGER :: ILBOUND(2)
INTEGER :: IUBOUND(2)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2)))

P=Z

END SUBROUTINE

SUBROUTINE RMSEIM2 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN) :: P1(:,:)
INTEGER (KIND=JPIM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
INTEGER (KIND=JPIM), POINTER, INTENT (IN) :: Z2(:,:)
INTEGER :: I

INTEGER :: I1,I2
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1

S = 0.0

DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2) - Z2(I1,I2))**2       

ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCIM3 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P(:,:,:)
INTEGER (KIND=JPIM), POINTER :: Z(:,:,:)

INTEGER :: ILBOUND(3)
INTEGER :: IUBOUND(3)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3)))

P=Z

END SUBROUTINE

SUBROUTINE RMSEIM3 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN) :: P1(:,:,:)
INTEGER (KIND=JPIM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
INTEGER (KIND=JPIM), POINTER, INTENT (IN) :: Z2(:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1

S = 0.0

DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3) - Z2(I1,I2,I3))**2       

ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCIM4 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P(:,:,:,:)
INTEGER (KIND=JPIM), POINTER :: Z(:,:,:,:)

INTEGER :: ILBOUND(4)
INTEGER :: IUBOUND(4)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4)))

P=Z

END SUBROUTINE

SUBROUTINE RMSEIM4 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN) :: P1(:,:,:,:)
INTEGER (KIND=JPIM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
INTEGER (KIND=JPIM), POINTER, INTENT (IN) :: Z2(:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1

S = 0.0

DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4) - Z2(I1,I2,I3,I4))**2       

ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE




SUBROUTINE ALLOCIM5 (P, Z)

INTEGER (KIND=JPIM), POINTER :: P(:,:,:,:,:)
INTEGER (KIND=JPIM), POINTER :: Z(:,:,:,:,:)

INTEGER :: ILBOUND(5)
INTEGER :: IUBOUND(5)

ILBOUND = LBOUND(Z)
IUBOUND = UBOUND(Z)


ALLOCATE (P (ILBOUND (1):IUBOUND (1),ILBOUND (2):IUBOUND (2),ILBOUND (3):IUBOUND (3),ILBOUND (4):IUBOUND (4),ILBOUND (5):IUBOUND&
    & (5)))

P=Z

END SUBROUTINE

SUBROUTINE RMSEIM5 (CDNAME, P1, KLUN, YDD)
CHARACTER (LEN=*) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN) :: P1(:,:,:,:,:)
INTEGER (KIND=JPIM) :: S
INTEGER, INTENT (IN) :: KLUN
TYPE (DD12), INTENT (IN) :: YDD
INTEGER (KIND=JPIM), POINTER, INTENT (IN) :: Z2(:,:,:,:,:)
INTEGER :: I

INTEGER :: I1,I2,I3,I4,I5
ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/CUCALLN_MF.OUT.dat', FORM='UNFORMATTED')

CALL LOAD (KLUN, Z2, KLBOUND=LBOUND (P1)) ! LBOUND (P1) = [1, 1, ...]

  IF (PRESENT (YDD)) THEN
    CALL YDD%SHUFFLE (Z2)
  ENDIF

IF (SIZE (P1, 1) /= SIZE (Z2, 1)) STOP 1
IF (SIZE (P1, 2) /= SIZE (Z2, 2)) STOP 1
IF (SIZE (P1, 3) /= SIZE (Z2, 3)) STOP 1
IF (SIZE (P1, 4) /= SIZE (Z2, 4)) STOP 1
IF (SIZE (P1, 5) /= SIZE (Z2, 5)) STOP 1

S = 0.0

DO I5 = 1, SIZE (P1, 5)
DO I4 = 1, SIZE (P1, 4)
DO I3 = 1, SIZE (P1, 3)
DO I2 = 1, SIZE (P1, 2)
DO I1 = 1, SIZE (P1, 1)
        S = S + (P1(I1,I2,I3,I4,I5) - Z2(I1,I2,I3,I4,I5))**2       

ENDDO
ENDDO
ENDDO
ENDDO
ENDDO

WRITE (0, *) '===>', 'RMSE:', CDNAME, '<==='
WRITE (0, *) __FILE__, ':', __LINE__
WRITE (0, *) 'RMSE:', CDNAME, '=', S


CLOSE (ILUNFO)

END SUBROUTINE


END
